package com.ubs.opi.domain;

import java.util.HashSet;
import java.util.Set;


/**
 * AclObjectIdentity generated by MyEclipse - Hibernate Tools
 */

public class AclObjectIdentity extends com.ubs.opi.domain.BaseDomain implements java.io.Serializable {

   static final long serialVersionUID = 13;

    // Fields

     private long id = Constants.NEW_DOMAIN_ID;
     private AclObjectIdentity aclObjectIdentity;
     private String objectIdentity;
     private String aclClass;
     private Set aclObjectIdentities = new HashSet(0);
     private Set aclPermissions = new HashSet(0);


    // Constructors

    /** default constructor */
    public AclObjectIdentity() {
    }

	/** minimal constructor */
    public AclObjectIdentity(String objectIdentity, String aclClass) {
        this.objectIdentity = objectIdentity;
        this.aclClass = aclClass;
    }

    /** full constructor */
    public AclObjectIdentity(AclObjectIdentity aclObjectIdentity, String objectIdentity, String aclClass, Set aclObjectIdentities, Set aclPermissions) {
        this.aclObjectIdentity = aclObjectIdentity;
        this.objectIdentity = objectIdentity;
        this.aclClass = aclClass;
        this.aclObjectIdentities = aclObjectIdentities;
        this.aclPermissions = aclPermissions;
    }


    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public AclObjectIdentity getAclObjectIdentity() {
        return this.aclObjectIdentity;
    }

    public void setAclObjectIdentity(AclObjectIdentity aclObjectIdentity) {
        this.aclObjectIdentity = aclObjectIdentity;
    }

    public String getObjectIdentity() {
        return this.objectIdentity;
    }

    public void setObjectIdentity(String objectIdentity) {
        this.objectIdentity = objectIdentity;
    }

    public String getAclClass() {
        return this.aclClass;
    }

    public void setAclClass(String aclClass) {
        this.aclClass = aclClass;
    }

    public Set getAclObjectIdentities() {
        return this.aclObjectIdentities;
    }

    public void setAclObjectIdentities(Set aclObjectIdentities) {
        this.aclObjectIdentities = aclObjectIdentities;
    }

    public Set getAclPermissions() {
        return this.aclPermissions;
    }

    public void setAclPermissions(Set aclPermissions) {
        this.aclPermissions = aclPermissions;
    }









}