package com.ubs.opi.domain;

import java.util.HashSet;
import java.util.Set;

/**
 * Advisor generated by MyEclipse - Hibernate Tools
 */

public class Advisor extends BaseDomain implements
      java.io.Serializable {

   // start added by paulmac
   static final long serialVersionUID = 0;

   private String transinvestortype; // holds the transient selection

   private String transproductname; // holds the transient selection

   private boolean acceptedtermsofuse = false;

   private Authorities authorities = new Authorities();

   // end added by paulmac

   // Fields
   private long id = Constants.NEW_DOMAIN_ID; // modified by paulmac

   private Individual individual;

   private Advisorfirm advisorfirm;

   private String isactivated = Constants.TRUE;

   private String assistantname;

   private String assistantemail;

   private Set<Application> applications = new HashSet<Application>();

   private Set<Advisorprovider> advisorproviders = new HashSet<Advisorprovider>(0);

   // Constructors

   // added by paulmac
   public Advisor(long id) {
      this.id = id;
   }

   /** default constructor */
   public Advisor() {
      // authorities.setAuthority(Authorities.AdvisorRole);
   }

   public Advisor(Individual individual) {
      this.individual = individual;
   }

   /** minimal constructor */
   public Advisor(String isactivated) {
      this.isactivated = isactivated;
   }

   /** full constructor */
   public Advisor(Advisorfirm advisorfirm, String isactivated,
         Individual individual, String assistantname, String assistantemail,
         Set<Advisorprovider> advisorproviders, Set<Application> applications) {

      this.advisorfirm = advisorfirm;
      this.individual = individual;
      this.isactivated = isactivated;
      this.assistantname = assistantname;
      this.assistantemail = assistantemail;
      this.applications = applications;
      this.advisorproviders = advisorproviders;
   }

   // Property accessors

   public long getId() {
      return this.id;
   }

   public void setId(long id) {
      this.id = id;
   }
   
   public String getPasswordconfirmed() {
      return this.getIndividual().getUsers().getPasswordconfirmed();
   }

   public String getIsactivated() {
      return this.isactivated;
   }

   public void setIsactivated(String isactivated) {
      if (isactivated == null)
         this.isactivated = "false";
      else
         this.isactivated = isactivated;
   }

   public Advisorfirm getAdvisorfirm() {
      return this.advisorfirm;
   }

   public void setAdvisorfirm(Advisorfirm advisorfirm) {
      this.advisorfirm = advisorfirm;
   }

   public Individual getIndividual() {
      return this.individual;
   }

   public void setIndividual(Individual individual) {
      this.individual = individual;
   }

   // added by paulmac
   public Application[] getApplicationsarray() {
      return (Application[]) this.applications.toArray(new Application[0]);
   }

   public Set<Advisorprovider> getAdvisorproviders() {
      return this.advisorproviders;
   }

   public void setAdvisorproviders(Set<Advisorprovider> advisorproviders) {
      this.advisorproviders = advisorproviders;
   }

   // added by paulmac
   public void addAdvisorproviders(Advisorprovider advisorprovider) {
      this.advisorproviders.add(advisorprovider);
   }

   // added by paulmac
   public void addApplications(Application application) {
      this.applications.add(application);
   }

   public Set<Application> getApplications() {
      return this.applications;
   }

   // added by paulmac
   public void setApplications(Set<Application> applications) {
      this.applications = (Set<Application>) applications; 
   }

   public String getTransinvestortype() {
      return transinvestortype;
   }

   public void setTransinvestortype(String transinvestortype) {
      this.transinvestortype = transinvestortype;
   }

   public String getTransproductname() {
      return transproductname;
   }

   public void setTransproductname(String transproductname) {
      this.transproductname = transproductname;
   }

   public Authorities getAuthorities() {
      return authorities;
   }

   public void setAuthorities(Authorities authorities) {
      this.authorities = authorities;
   }

   public String getAssistantemail() {
      return assistantemail;
   }

   public void setAssistantemail(String assistantemail) {
      this.assistantemail = assistantemail;
   }

   public String getAssistantname() {
      return assistantname;
   }

   public void setAssistantname(String assistantname) {
      this.assistantname = assistantname;
   }

   public boolean isAcceptedtermsofuse() {
      return acceptedtermsofuse;
   }

   public void setAcceptedtermsofuse(boolean acceptedtermsofuse) {
      this.acceptedtermsofuse = acceptedtermsofuse;
   }

//   // added by paulmac
//   public void update(Dwradvisor dwradv) {
//      this.getIndividual().getUsers().setUsername(dwradv.getUsername());
//      this.getIndividual().setFirstname(dwradv.getFirstname());
//      this.getIndividual().setLastname(dwradv.getLastname());
//      this.getIndividual().setWorkemail(dwradv.getWorkemail());
//      this.setAssistantname(dwradv.getAssistantname());
//      this.setAssistantemail(dwradv.getAssistantemail());
//   }
   
   public String toString() {
     return "{advisor: id=" + this.id + "}"; 
   }

}