package com.ubs.opi.domain;



/**
 * Advisorprovider generated by MyEclipse - Hibernate Tools
 */

public class Advisorprovider extends com.ubs.opi.domain.BaseDomain implements java.io.Serializable {


   static final long serialVersionUID = 15;

   // Fields

    private long id = Constants.NEW_DOMAIN_ID;
    private Advisor advisor;
    private Company company;
    private Individual individual;
    private String advisornumber;
    // added by paulmac
    private String transbdmid;

    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    // added by paulmac
    public String getAdvisorfullname() { 
       return this.getAdvisor().getIndividual().getFullname();
   }

    // added by paulmac
    public String getAdvisorfirmstate() { 
       return this.getAdvisor().getAdvisorfirm().getCompany().getState();
   }

    // added by paulmac
    public String getAdvisorfirmname() { 
       return this.getAdvisor().getAdvisorfirm().getCompany().getName();
   }

    // added by paulmac
    public String getDealergroupname() { 
       return this.getAdvisor().getAdvisorfirm().getDealergroup().getCompany().getName();
   }

    public Advisor getAdvisor() {
        return this.advisor;
    }

    public void setAdvisor(Advisor advisor) {
        this.advisor = advisor;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Individual getIndividual() {
        return this.individual;
    }

    public void setIndividual(Individual individual) {
        this.individual = individual;
    }

    public String getAdvisornumber() {
        return this.advisornumber;
    }

    public void setAdvisornumber(String advisornumber) {
        this.advisornumber = advisornumber;
    }

    // added by paulmac
   public String getTransbdmid()
   {
      return transbdmid;
   }

   // added by paulmac
   public void setTransbdmid(String transbdmid)
   {
      this.transbdmid = transbdmid;
   }

   public String toString() {
     return "{advisorProvider: id=" + this.id + "}";
   }
}