package com.ubs.opi.domain;

import java.util.HashSet;
import java.util.Set;


/**
 * Advisorfirm generated by MyEclipse - Hibernate Tools
 */

public class Advisorfirm extends com.ubs.opi.domain.BaseDomain implements java.io.Serializable {


   // added by paulmac
   static final long serialVersionUID = 1;
    // Fields

     private long id = Constants.NEW_DOMAIN_ID; // mod. by paulmac
     private Company company;
     private Dealergroup dealergroup;
     //private Set advisors = new HashSet(0);
     private Set<Advisor> advisors = new HashSet<Advisor>(0);

//     private String afname;
//     private String afabn;

    // Constructors

    public String getAfabn() {
      return this.getCompany().getAbn();
   }

   public void setAfabn(String afabn) {
      this.getCompany().setAbn(afabn);
   }

   public String getAfname() {
      return this.getCompany().getName();
   }

   public void setAfname(String afname) {
      this.getCompany().setName(afname);
   }

   /** default constructor */
    public Advisorfirm() {
    }

    public Advisorfirm(Company company, String abn) {
       this.company = company;
       this.company.setAbn(abn);
    }

    /** full constructor */
    public Advisorfirm(Company company, Dealergroup dealergroup, Set<Advisor> advisors) {
        this.company = company;
        this.dealergroup = dealergroup;
        this.advisors = advisors;
    }


    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Dealergroup getDealergroup() {
        return this.dealergroup;
    }

    public void setDealergroup(Dealergroup dealergroup) {
        this.dealergroup = dealergroup;
    }

    public Set<Advisor> getAdvisors() {
        return this.advisors;
    }

    public void setAdvisors(Set<Advisor> advisors) {
        this.advisors = advisors;
    }

    public String toString() {
      return this.company.getName() + "[abn=" + this.company.getAbn() + "]";
    }
}