package com.ubs.opi.domain;

import static com.ubs.opi.domain.Constants.CORPORATE_TRUST_TYPE;
import static com.ubs.opi.domain.Constants.CORPORATE_TYPE;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Application generated by MyEclipse - Hibernate Tools
 */
public class Application extends com.ubs.opi.domain.BaseDomain implements java.io.Serializable {
  //~ Constructors -------------------------------------------------------------

  public Application() {
    this.recordCreated = new Date(); // i.e now

    this.investorindividuals =
      new TreeSet<Investorindividual>(new InvestorindividualComp());
    this.beneficiaries =
      new TreeSet<Investorindividual>(new InvestorindividualComp());
    this.applicants =
      new TreeSet<Investorindividual>(new InvestorindividualComp());
  }

  //~ Methods ------------------------------------------------------------------

  public Application clone() {
    long i = Constants.NEW_DOMAIN_ID;
    Application application = new Application();
    application.setId(this.id++);
    application.setTemplate(this);
    application.setCreatedby(Utils.getUser().getUsername());

    if (this.company != null) {
      Company companyClone = company.clone(i++);
      application.company = companyClone;
    }

    if (this.trust != null) {
      Trust trustClone = trust.clone(i++);
      application.trust = trustClone;
    }

//       application.trust = trust;
    log.info("investorindividuals size=" + investorindividuals.size());

    Iterator itr = investorindividuals.iterator();

    while (itr.hasNext()) {
      Investorindividual investorindividual = (Investorindividual) itr.next();
      log.info(
        "investor name=" + investorindividual.getIndividual().getLastname());

      Investorindividual clone = investorindividual.clone();
      application.addInvestorindividual(clone);
    }

    application.advisor = advisor;
    application.product = product;
    application.commission = commission;
//       application.applicationnumber = applicationnumber;
//       application.clientnumber = clientnumber;
    application.accountdesignation = accountdesignation;
//       String [] strArray = StringUtils.tokenizeToStringArray(accountdesignation, " ", true, true);
    application.firstname = firstname;
    application.middlename = middlename;
    application.lastname = lastname;
    application.homephone = homephone;
    application.workphone = workphone;
    application.email = email;
    application.fax = fax;
    application.address1 = address1;
    application.address2 = address2;
    application.suburb = suburb;
    application.state = state;
    application.postcode = postcode;
    application.country = country;
    application.type = type;
    //application.applicationdate = new Date(); // i.e now
    application.recordCreated = new Date(); // i.e now
    application.isprovidercustomer = isprovidercustomer;
    application.islatest = Constants.TRUE;
    this.islatest = Constants.FALSE;
    application.reinvestdistribution = reinvestdistribution;
    application.directcreditdistribution = directcreditdistribution;
    application.providerunitholdernumber = providerunitholdernumber;
    application.providerfundname = providerfundname;
    application.isubscustomer = isubscustomer;
    application.ubsunitholdernumber = ubsunitholdernumber;
    application.ubsfundname = ubsfundname;
    application.ddapplicant = ddapplicant;
    application.ddabn = ddabn;
    application.ddinstitution = ddinstitution;
    application.ddinstitutionaddress = ddinstitutionaddress;
    application.ddinstitutionpostcode = ddinstitutionpostcode;
    application.ddinstitutionsuburb = ddinstitutionsuburb;
    application.ddaccountname = ddaccountname;
    application.ddbsb = ddbsb;
    application.ddaccountno = ddaccountno;
    application.ddAccountType = ddAccountType;
    application.status = Constants.DRAFT_STATUS;

//       application.paymentstatus = Constants.PAY_STATE_PENDING_KEY;
    return application;
  }
  

  /**
   * Finds an investorindividual for the given application of the given id.
   * 
   * @param application The application.
   * @param investorIndividualId The investorindividual's id.
   * 
   * @return The investor individual.
   */
  public Investorindividual findInvestorIndividualById(Long investorIndividualId) {
    Investorindividual investorindividual = null;
    
    for (Investorindividual tmp : this.getInvestorindividuals()) {
      if (tmp.getId().equals(investorIndividualId)) {
        investorindividual = tmp;
        break;
      }
    }
    
    return investorindividual;
  }
  
  /**
   * Gets all investor individuals associated to this application that
   * are elegible to act as guarantors.
   * 
   * @param application The application to check.
   * 
   * @return Elegible guarantors associated to the given application.
   */
  public Set<Investorindividual> getElegibleAdditionalGuarantors() {
    Set<Investorindividual> elegibleGuarantors = new HashSet<Investorindividual>();
    
    for (Investorindividual investorindividual : this.getInvestorindividuals()) {
      // directors already had the option to be marked as guarantors.
      if (investorindividual.getRole().equals(Constants.DIRECTOR)) {
        continue;
      }
      
      // remove external guarantors.  they are seperate to this logic.
      if (investorindividual.getRole().equals(Constants.GUARANTOR)) {
        continue;
      }
      
      elegibleGuarantors.add(investorindividual);
    }
    
    return elegibleGuarantors;
  }
  
  /**
   * Gets the external guarantor for this application, if any.
   * 
   * @return The IndividualInvestor representing the external guarantor, or
   *         <code>null</code> if none found.
   */
  public Investorindividual getExternalGuarantor() {
    Investorindividual externalGuarantor = null;
    
    for (Investorindividual investorindividual : this.investorindividuals) {
      if (investorindividual.getRole().equals(Constants.GUARANTOR)) {
        externalGuarantor = investorindividual;
        break;
      }
    }
    
    return externalGuarantor;
  }
  
  /**
   * Checks for any non-external guarantors.  Excludes corporate directors.
   * 
   * @return Internal guarantors.
   */
  public Investorindividual getInternalGuarantor() {
    Investorindividual additionalGuarantor = null;
    
    for (Investorindividual investorindividual : this.investorindividuals) {
      if (!investorindividual.getRole().equals(Constants.GUARANTOR)
          && !investorindividual.getRole().equals(Constants.DIRECTOR)
          && investorindividual.getIsguarantor().equals(Constants.TRUE)) {
        additionalGuarantor = investorindividual;
        break;
      }
    }
    
    return additionalGuarantor;
  }

  public String toString() {
    return "{appliction: id=" + this.id + ", accountDesignation=" +
           this.accountdesignation + ", applicationType = " +
           this.getDisplaypaymentmethod() + "}";
  }

  public boolean isHasAdditionalGuarantor() {
    return this.getExternalGuarantor() != null || 
           this.getInternalGuarantor() != null;
  }

  public boolean isStatusapproved() {
    if ((status == Constants.CONDITIONAL_APPROVAL_STATUS.longValue()) ||
        (status == Constants.APPROVED_STATUS.longValue()))
      statusapproved = true;

    return statusapproved;
  }

  // added by paulmac
  public boolean isSoledirector() {
    if ((this.type == Constants.CORPORATE_TYPE) ||
        (this.type == Constants.CORPORATE_TRUST_TYPE)) {
      for (Investorindividual individual : investorindividuals) {
        if (individual.getIssoledirector().equals(Constants.TRUE))
          return true;
      }
    }

    return false;
  }

  public boolean isHasSufficientDirectors() {
    return ((this.type == CORPORATE_TYPE) ||
           (this.type == CORPORATE_TRUST_TYPE)) &&
           (this.isSoledirector() || (this.investorindividuals.size() == 2));
  }

  public boolean isUnbounded() {
    return (type > Constants.JOINT_TYPE.longValue());
  }

  public String getDisplaytype() {
    return Utils.getInvestortypes().get(new Long(type));
  }
  
  public String getProductname() {
    return this.getProduct().getName();
  }

  public long getId() {
    this.beneficiaryindex = 0;
    this.applicantindex = 0;
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public Company getCompany() {
    return this.company;
  }

  public void setCompany(Company company) {
    this.company = company;
  }

  public Advisor getAdvisor() {
    return this.advisor;
  }

  public void setAdvisor(Advisor advisor) {
    this.advisor = advisor;
  }

  public Product getProduct() {
    return this.product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }

  public Trust getTrust() {
    return this.trust;
  }

  public void setTrust(Trust trust) {
    this.trust = trust;
  }

  public double getCommission() {
    return this.commission;
  }

  public void setCommission(double commission) {
    this.commission = commission;
  }

  public String getApplicationnumber() {
    return this.applicationnumber;
  }

  public void setApplicationnumber(String applicationnumber) {
    this.applicationnumber = applicationnumber;
  }

  public String getClientnumber() {
    return this.clientnumber;
  }

  public void setClientnumber(String clientnumber) {
    this.clientnumber = clientnumber;
  }

  public String getAccountdesignation() {
    return this.accountdesignation;
  }

  public void setAccountdesignation(String accountdesignation) {
    this.accountdesignation = accountdesignation;
  }

  public String getFirstname() {
    return this.firstname;
  }

  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  public String getMiddlename() {
    return this.middlename;
  }

  public void setMiddlename(String middlename) {
    this.middlename = middlename;
  }

  public String getLastname() {
    return this.lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public String getHomephone() {
    return this.homephone;
  }

  public void setHomephone(String homephone) {
    this.homephone = homephone;
  }

  public String getWorkphone() {
    return this.workphone;
  }

  public void setWorkphone(String workphone) {
    this.workphone = workphone;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getFax() {
    return this.fax;
  }

  public void setFax(String fax) {
    this.fax = fax;
  }

  public String getAddress1() {
    return this.address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public String getAddress2() {
    return this.address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public String getSuburb() {
    return this.suburb;
  }

  public void setSuburb(String suburb) {
    this.suburb = suburb;
  }

  public String getState() {
    return this.state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public String getPostcode() {
    return this.postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public String getCountry() {
    return this.country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public long getType() {
    return this.type;
  }

  public void setType(long type) {
    this.type = type;
  }

  public long getStatus() {
    return this.status;
  }

  public void setStatus(long status) {
    this.status = status;
  }

  public long getPaymentstatus() {
    return this.paymentstatus;
  }

  public void setPaymentstatus(long paymentstatus) {
    this.paymentstatus = paymentstatus;
  }

  public String getIsborrowingfromubs() {
    return this.isborrowingfromubs;
  }

  public void setIsborrowingfromubs(String isborrowingfromubs) {
    if (isborrowingfromubs == null)
      this.isborrowingfromubs = "false";
    else
      this.isborrowingfromubs = isborrowingfromubs;
  }

  public String getIspurchasingputfromubs() {
    return this.ispurchasingputfromubs;
  }

  public void setIspurchasingputfromubs(String ispurchasingputfromubs) {
    if (ispurchasingputfromubs == null)
      this.isborrowingfromubs = "false";
    else
      this.ispurchasingputfromubs = ispurchasingputfromubs;
  }

  public String getIsial() {
    return this.isial;
  }

  public void setIsial(String isial) {
    if (isial == null)
      this.isial = "false";
    else
      this.isial = isial;
  }

  public String getIseithertosign() {
    return this.iseithertosign;
  }

  public void setIseithertosign(String iseithertosign) {
    if (iseithertosign == null)
      this.iseithertosign = "false";
    else
      this.iseithertosign = iseithertosign;
  }

  public String getIspapercopywanted() {
    return this.ispapercopywanted;
  }

  public void setIspapercopywanted(String ispapercopywanted) {
    if (ispapercopywanted == null)
      this.ispapercopywanted = "false";
    else
      this.ispapercopywanted = ispapercopywanted;
  }

  public String getIsprovidercustomer() {
    return this.isprovidercustomer;
  }

  public void setIsprovidercustomer(String isprovidercustomer) {
    if (isprovidercustomer == null)
      this.isprovidercustomer = "false";
    else
      this.isprovidercustomer = isprovidercustomer;
  }

  public String getIslatest() {
    return this.islatest;
  }

  public void setIslatest(String islatest) {
    if (islatest == null)
      this.islatest = "false";
    else
      this.islatest = islatest;
  }

  public String getReinvestdistribution() {
    return this.reinvestdistribution;
  }

  public void setReinvestdistribution(String reinvestdistribution) {
    if (reinvestdistribution == null)
      this.reinvestdistribution = "false";
    else
      this.reinvestdistribution = reinvestdistribution;
  }

  public String getDirectcreditdistribution() {
    return this.directcreditdistribution;
  }

  public void setDirectcreditdistribution(String directcreditdistribution) {
    if (directcreditdistribution == null)
      this.directcreditdistribution = "false";
    else
      this.directcreditdistribution = directcreditdistribution;
  }

  public String getProviderunitholdernumber() {
    return this.providerunitholdernumber;
  }

  public void setProviderunitholdernumber(String providerunitholdernumber) {
    this.providerunitholdernumber = providerunitholdernumber;
  }

  public String getProviderfundname() {
    return this.providerfundname;
  }

  public void setProviderfundname(String providerfundname) {
    this.providerfundname = providerfundname;
  }

  public String getIsubscustomer() {
    return this.isubscustomer;
  }

  public void setIsubscustomer(String isubscustomer) {
    if (isubscustomer == null)
      this.isubscustomer = "false";
    else
      this.isubscustomer = isubscustomer;
  }

  public String getUbsunitholdernumber() {
    return this.ubsunitholdernumber;
  }

  public void setUbsunitholdernumber(String ubsunitholdernumber) {
    this.ubsunitholdernumber = ubsunitholdernumber;
  }

  public String getUbsfundname() {
    return this.ubsfundname;
  }

  public void setUbsfundname(String ubsfundname) {
    this.ubsfundname = ubsfundname;
  }

  public String getDdapplicant() {
    return this.ddapplicant;
  }

  public void setDdapplicant(String ddapplicant) {
    this.ddapplicant = ddapplicant;
  }

  public String getDdabn() {
    return this.ddabn;
  }

  public void setDdabn(String ddabn) {
    this.ddabn = ddabn;
  }

  public String getDdinstitution() {
    return this.ddinstitution;
  }

  public void setDdinstitution(String ddinstitution) {
    this.ddinstitution = ddinstitution;
  }

  public String getDdinstitutionaddress() {
    return this.ddinstitutionaddress;
  }

  public void setDdinstitutionaddress(String ddinstitutionaddress) {
    this.ddinstitutionaddress = ddinstitutionaddress;
  }

  public String getDdinstitutionpostcode() {
    return this.ddinstitutionpostcode;
  }

  public void setDdinstitutionpostcode(String ddinstitutionpostcode) {
    this.ddinstitutionpostcode = ddinstitutionpostcode;
  }

  public String getDdinstitutionstate() {
    return this.ddinstitutionstate;
  }

  public void setDdinstitutionstate(String ddinstitutionstate) {
    this.ddinstitutionstate = ddinstitutionstate;
  }

  public String getDdinstitutionsuburb() {
    return this.ddinstitutionsuburb;
  }

  public void setDdinstitutionsuburb(String ddinstitutionsuburb) {
    this.ddinstitutionsuburb = ddinstitutionsuburb;
  }

  public String getDdaccountname() {
    return this.ddaccountname;
  }

  public void setDdaccountname(String ddaccountname) {
    this.ddaccountname = ddaccountname;
  }

  public String getDdbsb() {
    return this.ddbsb;
  }

  public void setDdbsb(String ddbsb) {
    this.ddbsb = ddbsb;
  }

  public String getDdaccountno() {
    return this.ddaccountno;
  }

  public void setDdaccountno(String ddaccountno) {
    this.ddaccountno = ddaccountno;
  }

  public long getIcash() {
    return this.icash;
  }

  public void setIcash(long icash) {
    this.icash = icash;
  }

  public long getIshares() {
    return this.ishares;
  }

  public void setIshares(long ishares) {
    this.ishares = ishares;
  }

  public long getIotherliquid() {
    return this.iotherliquid;
  }

  public void setIotherliquid(long iotherliquid) {
    this.iotherliquid = iotherliquid;
  }

  public long getIresidentialproperty() {
    return this.iresidentialproperty;
  }

  public void setIresidentialproperty(long iresidentialproperty) {
    this.iresidentialproperty = iresidentialproperty;
  }

  public long getIinvestmentproperty() {
    return this.iinvestmentproperty;
  }

  public void setIinvestmentproperty(long iinvestmentproperty) {
    this.iinvestmentproperty = iinvestmentproperty;
  }

  public long getIotherassets() {
    return this.iotherassets;
  }

  public void setIotherassets(long iotherassets) {
    this.iotherassets = iotherassets;
  }

  public String getIotherassetsdetails() {
    return this.iotherassetsdetails;
  }

  public void setIotherassetsdetails(String iotherassetsdetails) {
    this.iotherassetsdetails = iotherassetsdetails;
  }

  public long getIotherloanssecured() {
    return this.iotherloanssecured;
  }

  public void setIotherloanssecured(long iotherloanssecured) {
    this.iotherloanssecured = iotherloanssecured;
  }

  public long getIloansresidentialproperty() {
    return this.iloansresidentialproperty;
  }

  public void setIloansresidentialproperty(long iloansresidentialproperty) {
    this.iloansresidentialproperty = iloansresidentialproperty;
  }

  public long getIloansinvestmentproperty() {
    return this.iloansinvestmentproperty;
  }

  public void setIloansinvestmentproperty(long iloansinvestmentproperty) {
    this.iloansinvestmentproperty = iloansinvestmentproperty;
  }

  public long getIloanspersonalunsecured() {
    return this.iloanspersonalunsecured;
  }

  public void setIloanspersonalunsecured(long iloanspersonalunsecured) {
    this.iloanspersonalunsecured = iloanspersonalunsecured;
  }

  public long getIguaranteesgranted() {
    return this.iguaranteesgranted;
  }

  public void setIguaranteesgranted(long iguaranteesgranted) {
    this.iguaranteesgranted = iguaranteesgranted;
  }

  public long getIotherliabilities() {
    return this.iotherliabilities;
  }

  public void setIotherliabilities(long iotherliabilities) {
    this.iotherliabilities = iotherliabilities;
  }

  public String getIotherliabilitiesdetails() {
    return this.iotherliabilitiesdetails;
  }

  public void setIotherliabilitiesdetails(String iotherliabilitiesdetails) {
    this.iotherliabilitiesdetails = iotherliabilitiesdetails;
  }

  public long getIsalary() {
    return this.isalary;
  }

  public void setIsalary(long isalary) {
    this.isalary = isalary;
  }

  public long getIrentalanddividend() {
    return this.irentalanddividend;
  }

  public void setIrentalanddividend(long irentalanddividend) {
    this.irentalanddividend = irentalanddividend;
  }

  public long getIotherincome() {
    return this.iotherincome;
  }

  public void setIotherincome(long iotherincome) {
    this.iotherincome = iotherincome;
  }

  public String getIotherincomedetails() {
    return this.iotherincomedetails;
  }

  public void setIotherincomedetails(String iotherincomedetails) {
    this.iotherincomedetails = iotherincomedetails;
  }

  public long getItaxpayable() {
    return this.itaxpayable;
  }

  public void setItaxpayable(long itaxpayable) {
    this.itaxpayable = itaxpayable;
  }

  public Date getItaxpayabledate() {
    return this.itaxpayabledate;
  }

  public void setItaxpayabledate(Date itaxpayabledate) {
    this.itaxpayabledate = itaxpayabledate;
  }

  public long getIinterestonsecuredloans() {
    return this.iinterestonsecuredloans;
  }

  public void setIinterestonsecuredloans(long iinterestonsecuredloans) {
    this.iinterestonsecuredloans = iinterestonsecuredloans;
  }

  public long getIinterestonunsecuredloans() {
    return this.iinterestonunsecuredloans;
  }

  public void setIinterestonunsecuredloans(long iinterestonunsecuredloans) {
    this.iinterestonunsecuredloans = iinterestonunsecuredloans;
  }

  public long getIlivingexpenses() {
    return this.ilivingexpenses;
  }

  public void setIlivingexpenses(long ilivingexpenses) {
    this.ilivingexpenses = ilivingexpenses;
  }

  public long getIotherexpenses() {
    return this.iotherexpenses;
  }

  public void setIotherexpenses(long iotherexpenses) {
    this.iotherexpenses = iotherexpenses;
  }

  public String getIotherexpensesdetails() {
    return this.iotherexpensesdetails;
  }

  public void setIotherexpensesdetails(String iotherexpensesdetails) {
    this.iotherexpensesdetails = iotherexpensesdetails;
  }

  public long getGcash() {
    return this.gcash;
  }

  public void setGcash(long gcash) {
    this.gcash = gcash;
  }

  public long getGshares() {
    return this.gshares;
  }

  public void setGshares(long gshares) {
    this.gshares = gshares;
  }

  public long getGotherliquid() {
    return this.gotherliquid;
  }

  public void setGotherliquid(long gotherliquid) {
    this.gotherliquid = gotherliquid;
  }

  public long getGresidentialproperty() {
    return this.gresidentialproperty;
  }

  public void setGresidentialproperty(long gresidentialproperty) {
    this.gresidentialproperty = gresidentialproperty;
  }

  public long getGinvestmentproperty() {
    return this.ginvestmentproperty;
  }

  public void setGinvestmentproperty(long ginvestmentproperty) {
    this.ginvestmentproperty = ginvestmentproperty;
  }

  public long getGotherassets() {
    return this.gotherassets;
  }

  public void setGotherassets(long gotherassets) {
    this.gotherassets = gotherassets;
  }

  public String getGotherassetsdetails() {
    return this.gotherassetsdetails;
  }

  public void setGotherassetsdetails(String gotherassetsdetails) {
    this.gotherassetsdetails = gotherassetsdetails;
  }

  public long getGotherloanssecured() {
    return this.gotherloanssecured;
  }

  public void setGotherloanssecured(long gotherloanssecured) {
    this.gotherloanssecured = gotherloanssecured;
  }

  public long getGloansresidentialproperty() {
    return this.gloansresidentialproperty;
  }

  public void setGloansresidentialproperty(long gloansresidentialproperty) {
    this.gloansresidentialproperty = gloansresidentialproperty;
  }

  public long getGloansinvestmentproperty() {
    return this.gloansinvestmentproperty;
  }

  public void setGloansinvestmentproperty(long gloansinvestmentproperty) {
    this.gloansinvestmentproperty = gloansinvestmentproperty;
  }

  public long getGloanspersonalunsecured() {
    return this.gloanspersonalunsecured;
  }

  public void setGloanspersonalunsecured(long gloanspersonalunsecured) {
    this.gloanspersonalunsecured = gloanspersonalunsecured;
  }

  public long getGguaranteesgranted() {
    return this.gguaranteesgranted;
  }

  public void setGguaranteesgranted(long gguaranteesgranted) {
    this.gguaranteesgranted = gguaranteesgranted;
  }

  public long getGotherliabilities() {
    return this.gotherliabilities;
  }

  public void setGotherliabilities(long gotherliabilities) {
    this.gotherliabilities = gotherliabilities;
  }

  public String getGotherliabilitiesdetails() {
    return this.gotherliabilitiesdetails;
  }

  public void setGotherliabilitiesdetails(String gotherliabilitiesdetails) {
    this.gotherliabilitiesdetails = gotherliabilitiesdetails;
  }

  public long getGsalary() {
    return this.gsalary;
  }

  public void setGsalary(long gsalary) {
    this.gsalary = gsalary;
  }

  public long getGrentalanddividend() {
    return this.grentalanddividend;
  }

  public void setGrentalanddividend(long grentalanddividend) {
    this.grentalanddividend = grentalanddividend;
  }

  public long getGotherincome() {
    return this.gotherincome;
  }

  public void setGotherincome(long gotherincome) {
    this.gotherincome = gotherincome;
  }

  public String getGotherincomedetails() {
    return this.gotherincomedetails;
  }

  public void setGotherincomedetails(String gotherincomedetails) {
    this.gotherincomedetails = gotherincomedetails;
  }

  public long getGtaxpayable() {
    return this.gtaxpayable;
  }

  public void setGtaxpayable(long gtaxpayable) {
    this.gtaxpayable = gtaxpayable;
  }

  public Date getGtaxpayabledate() {
    return this.gtaxpayabledate;
  }

  public void setGtaxpayabledate(Date gtaxpayabledate) {
    this.gtaxpayabledate = gtaxpayabledate;
  }

  public long getGinterestonsecuredloans() {
    return this.ginterestonsecuredloans;
  }

  public void setGinterestonsecuredloans(long ginterestonsecuredloans) {
    this.ginterestonsecuredloans = ginterestonsecuredloans;
  }

  public long getGinterestonunsecuredloans() {
    return this.ginterestonunsecuredloans;
  }

  public void setGinterestonunsecuredloans(long ginterestonunsecuredloans) {
    this.ginterestonunsecuredloans = ginterestonunsecuredloans;
  }

  public long getGlivingexpenses() {
    return this.glivingexpenses;
  }

  public void setGlivingexpenses(long glivingexpenses) {
    this.glivingexpenses = glivingexpenses;
  }

  public long getGotherexpenses() {
    return this.gotherexpenses;
  }

  public void setGotherexpenses(long gotherexpenses) {
    this.gotherexpenses = gotherexpenses;
  }

  public String getGotherexpensesdetails() {
    return this.gotherexpensesdetails;
  }

  public void setGotherexpensesdetails(String gotherexpensesdetails) {
    this.gotherexpensesdetails = gotherexpensesdetails;
  }

  public long getOnboardingstatus() {
    return this.onboardingstatus;
  }

  public void setOnboardingstatus(long onboardingstatus) {
    this.onboardingstatus = onboardingstatus;
  }

  public String getOnboardinglastuser() {
    return this.onboardinglastuser;
  }

  public void setOnboardinglastuser(String onboardinglastuser) {
    this.onboardinglastuser = onboardinglastuser;
  }

  public String getOnboardingcomments() {
    return this.onboardingcomments;
  }

  public void setOnboardingcomments(String onboardingcomments) {
    this.onboardingcomments = onboardingcomments;
  }

  public String getOnboardinghardcopysighted() {
    return this.onboardinghardcopysighted;
  }

  public void setOnboardinghardcopysighted(String onboardinghardcopysighted) {
    this.onboardinghardcopysighted = onboardinghardcopysighted;
  }

  public String getDadealergroup() {
    return this.dadealergroup;
  }

  public void setDadealergroup(String dadealergroup) {
    this.dadealergroup = dadealergroup;
  }

  public long getCreditstatus() {
    return this.creditstatus;
  }

  public void setCreditstatus(long creditstatus) {
    this.creditstatus = creditstatus;
  }

  public String getCreditlastuser() {
    return this.creditlastuser;
  }

  public void setCreditlastuser(String creditlastuser) {
    this.creditlastuser = creditlastuser;
  }

  public String getCreditcomments() {
    return this.creditcomments;
  }

  public void setCreditcomments(String creditcomments) {
    this.creditcomments = creditcomments;
  }

  public String getCasapproved() {
    return this.casapproved;
  }

  public void setCasapproved(String casapproved) {
    this.casapproved = casapproved;
  }

  public String getBaycorpsapproved() {
    return this.baycorpsapproved;
  }

  public void setBaycorpsapproved(String baycorpsapproved) {
    this.baycorpsapproved = baycorpsapproved;
  }

  public long getAmlstatus() {
    return this.amlstatus;
  }

  public void setAmlstatus(long amlstatus) {
    this.amlstatus = amlstatus;
  }

  public String getAmllastuser() {
    return this.amllastuser;
  }

  public void setAmllastuser(String amllastuser) {
    this.amllastuser = amllastuser;
  }

  public String getAmlcomments() {
    return this.amlcomments;
  }

  public void setAmlcomments(String amlcomments) {
    this.amlcomments = amlcomments;
  }

  public String getAmlhardcopysighted() {
    return this.amlhardcopysighted;
  }

  public void setAmlhardcopysighted(String amlhardcopysighted) {
    this.amlhardcopysighted = amlhardcopysighted;
  }

  public String getCreditcheckverified() {
    return this.creditcheckverified;
  }

  public void setCreditcheckverified(String creditcheckverified) {
    this.creditcheckverified = creditcheckverified;
  }

  public String getGridcheckverified() {
    return this.gridcheckverified;
  }

  public void setGridcheckverified(String gridcheckverified) {
    this.gridcheckverified = gridcheckverified;
  }

  public String getWorldcheckverified() {
    return this.worldcheckverified;
  }

  public void setWorldcheckverified(String worldcheckverified) {
    this.worldcheckverified = worldcheckverified;
  }

  public String getGooglecheckverified() {
    return this.googlecheckverified;
  }

  public void setGooglecheckverified(String googlecheckverified) {
    this.googlecheckverified = googlecheckverified;
  }

  public String getTrustchecksverified() {
    return this.trustchecksverified;
  }

  public void setTrustchecksverified(String trustchecksverified) {
    this.trustchecksverified = trustchecksverified;
  }

  public String getOperationscomments() {
    return this.operationscomments;
  }

  public void setOperationscomments(String operationscomments) {
    this.operationscomments = operationscomments;
  }

  public long getBank3rdpartyauthorisation() {
    return this.bank3rdpartyauthorisation;
  }

  public void setBank3rdpartyauthorisation(long bank3rdpartyauthorisation) {
    this.bank3rdpartyauthorisation = bank3rdpartyauthorisation;
  }

  public String getBillingapproved() {
    return this.billingapproved;
  }

  public void setBillingapproved(String billingapproved) {
    this.billingapproved = billingapproved;
  }

  public String getReconciledbillingdata() {
    return this.reconciledbillingdata;
  }

  public void setReconciledbillingdata(String reconciledbillingdata) {
    this.reconciledbillingdata = reconciledbillingdata;
  }

  public String getGeneratedbillingdata() {
    return this.generatedbillingdata;
  }

  public void setGeneratedbillingdata(String generatedbillingdata) {
    this.generatedbillingdata = generatedbillingdata;
  }

  public String getAmountduepaid() {
    return this.amountduepaid;
  }

  public void setAmountduepaid(String amountduepaid) {
    this.amountduepaid = amountduepaid;
  }

  public Date getScheduleddddate() {
    return this.scheduleddddate;
  }

  public void setScheduleddddate(Date scheduleddddate) {
    this.scheduleddddate = scheduleddddate;
  }

  public String getDdpaymentsuccessful() {
    return this.ddpaymentsuccessful;
  }

  public void setDdpaymentsuccessful(String ddpaymentsuccessful) {
    this.ddpaymentsuccessful = ddpaymentsuccessful;
  }

  public String getDdunsuccessfulreason() {
    return this.ddunsuccessfulreason;
  }

  public void setDdunsuccessfulreason(String ddunsuccessfulreason) {
    this.ddunsuccessfulreason = ddunsuccessfulreason;
  }

  public String getInitialpaymentbycheque() {
    return this.initialpaymentbycheque;
  }

  public void setInitialpaymentbycheque(String initialpaymentbycheque) {
    this.initialpaymentbycheque = initialpaymentbycheque;
  }

  public double getPaymentbyalternativemeans() {
    return this.paymentbyalternativemeans;
  }

  public void setPaymentbyalternativemeans(double paymentbyalternativemeans) {
    this.paymentbyalternativemeans = paymentbyalternativemeans;
  }

  public String getConductedbilling() {
    return this.conductedbilling;
  }

  public void setConductedbilling(String conductedbilling) {
    this.conductedbilling = conductedbilling;
  }

  public String getGeneratedapprovalletter() {
    return this.generatedapprovalletter;
  }

  public void setGeneratedapprovalletter(String generatedapprovalletter) {
    this.generatedapprovalletter = generatedapprovalletter;
  }

  public String getGeneratedrejectionletter() {
    return this.generatedrejectionletter;
  }

  public void setGeneratedrejectionletter(String generatedrejectionletter) {
    this.generatedrejectionletter = generatedrejectionletter;
  }

  public String getAdministrationcomments() {
    return this.administrationcomments;
  }

  public void setAdministrationcomments(String administrationcomments) {
    this.administrationcomments = administrationcomments;
  }

  public String getOnboardinginfo1satisfied() {
    return this.onboardinginfo1satisfied;
  }

  public void setOnboardinginfo1satisfied(String onboardinginfo1satisfied) {
    this.onboardinginfo1satisfied = onboardinginfo1satisfied;
  }

  public String getOnboardinginfo1commentary() {
    return this.onboardinginfo1commentary;
  }

  public void setOnboardinginfo1commentary(String onboardinginfo1commentary) {
    this.onboardinginfo1commentary = onboardinginfo1commentary;
  }

  public String getOnboardinginfo2satisfied() {
    return this.onboardinginfo2satisfied;
  }

  public void setOnboardinginfo2satisfied(String onboardinginfo2satisfied) {
    this.onboardinginfo2satisfied = onboardinginfo2satisfied;
  }

  public String getOnboardinginfo2commentary() {
    return this.onboardinginfo2commentary;
  }

  public void setOnboardinginfo2commentary(String onboardinginfo2commentary) {
    this.onboardinginfo2commentary = onboardinginfo2commentary;
  }

  public String getOnboardinginfo3satisfied() {
    return this.onboardinginfo3satisfied;
  }

  public void setOnboardinginfo3satisfied(String onboardinginfo3satisfied) {
    this.onboardinginfo3satisfied = onboardinginfo3satisfied;
  }

  public String getOnboardinginfo3commentary() {
    return this.onboardinginfo3commentary;
  }

  public void setOnboardinginfo3commentary(String onboardinginfo3commentary) {
    this.onboardinginfo3commentary = onboardinginfo3commentary;
  }

  public String getCreditinfo1satisfied() {
    return this.creditinfo1satisfied;
  }

  public void setCreditinfo1satisfied(String creditinfo1satisfied) {
    this.creditinfo1satisfied = creditinfo1satisfied;
  }

  public String getCreditinfo1commentary() {
    return this.creditinfo1commentary;
  }

  public void setCreditinfo1commentary(String creditinfo1commentary) {
    this.creditinfo1commentary = creditinfo1commentary;
  }

  public String getCreditinfo2satisfied() {
    return this.creditinfo2satisfied;
  }

  public void setCreditinfo2satisfied(String creditinfo2satisfied) {
    this.creditinfo2satisfied = creditinfo2satisfied;
  }

  public String getCreditinfo2commentary() {
    return this.creditinfo2commentary;
  }

  public void setCreditinfo2commentary(String creditinfo2commentary) {
    this.creditinfo2commentary = creditinfo2commentary;
  }

  public String getCreditinfo3satisfied() {
    return this.creditinfo3satisfied;
  }

  public void setCreditinfo3satisfied(String creditinfo3satisfied) {
    this.creditinfo3satisfied = creditinfo3satisfied;
  }

  public String getCreditinfo3commentary() {
    return this.creditinfo3commentary;
  }

  public void setCreditinfo3commentary(String creditinfo3commentary) {
    this.creditinfo3commentary = creditinfo3commentary;
  }

  public String getAmlinfo1satisfied() {
    return this.amlinfo1satisfied;
  }

  public void setAmlinfo1satisfied(String amlinfo1satisfied) {
    this.amlinfo1satisfied = amlinfo1satisfied;
  }

  public String getAmlinfo1commentary() {
    return this.amlinfo1commentary;
  }

  public void setAmlinfo1commentary(String amlinfo1commentary) {
    this.amlinfo1commentary = amlinfo1commentary;
  }

  public String getAmlinfo2satisfied() {
    return this.amlinfo2satisfied;
  }

  public void setAmlinfo2satisfied(String amlinfo2satisfied) {
    this.amlinfo2satisfied = amlinfo2satisfied;
  }

  public String getAmlinfo2commentary() {
    return this.amlinfo2commentary;
  }

  public void setAmlinfo2commentary(String amlinfo2commentary) {
    this.amlinfo2commentary = amlinfo2commentary;
  }

  public String getAmlinfo3satisfied() {
    return this.amlinfo3satisfied;
  }

  public void setAmlinfo3satisfied(String amlinfo3satisfied) {
    this.amlinfo3satisfied = amlinfo3satisfied;
  }

  public String getAmlinfo3commentary() {
    return this.amlinfo3commentary;
  }

  public void setAmlinfo3commentary(String amlinfo3commentary) {
    this.amlinfo3commentary = amlinfo3commentary;
  }

  public Date getApplicationdate() {
    return this.applicationdate;
  }

  public void setApplicationdate(Date applicationdate) {
    this.applicationdate = applicationdate;
  }

  public String getCreatedby() {
    return this.createdby;
  }

  public void setCreatedby(String createdby) {
    this.createdby = createdby;
  }

  public String getModifiedby() {
    return this.modifiedby;
  }

  public void setModifiedby(String modifiedby) {
    this.modifiedby = modifiedby;
  }

  public Date getSoftcopyreceiveddate() {
    return this.softcopyreceiveddate;
  }

  public void setSoftcopyreceiveddate(Date softcopyreceiveddate) {
    this.softcopyreceiveddate = softcopyreceiveddate;
  }

  public String getChequeforubsattached() {
    return this.chequeforubsattached;
  }

  public void setChequeforubsattached(String chequeforubsattached) {
    this.chequeforubsattached = chequeforubsattached;
  }

  public String getChequereturned() {
    return this.chequereturned;
  }

  public void setChequereturned(String chequereturned) {
    this.chequereturned = chequereturned;
  }

  public String getChequeaccepted() {
    return this.chequeaccepted;
  }

  public void setChequeaccepted(String chequeaccepted) {
    this.chequeaccepted = chequeaccepted;
  }

  public String getIsreferredtocrc() {
    return this.isreferredtocrc;
  }

  public void setIsreferredtocrc(String isreferredtocrc) {
    this.isreferredtocrc = isreferredtocrc;
  }

  public String getFirstddstatusfailed() {
    return this.firstddstatusfailed;
  }

  public void setFirstddstatusfailed(String firstddstatusfailed) {
    this.firstddstatusfailed = firstddstatusfailed;
  }

  public String getFirstddstatussucceeded() {
    return this.firstddstatussucceeded;
  }

  public void setFirstddstatussucceeded(String firstddstatussucceeded) {
    this.firstddstatussucceeded = firstddstatussucceeded;
  }

  public Date getFirstddstatusdate() {
    return this.firstddstatusdate;
  }

  public void setFirstddstatusdate(Date firstddstatusdate) {
    this.firstddstatusdate = firstddstatusdate;
  }

  public String getIsseconddd() {
    return this.isseconddd;
  }

  public void setIsseconddd(String isseconddd) {
    this.isseconddd = isseconddd;
  }

  public Date getSecondscheduleddddate() {
    return this.secondscheduleddddate;
  }

  public void setSecondscheduleddddate(Date secondscheduleddddate) {
    this.secondscheduleddddate = secondscheduleddddate;
  }

  public String getSecondddstatusfailed() {
    return this.secondddstatusfailed;
  }

  public void setSecondddstatusfailed(String secondddstatusfailed) {
    this.secondddstatusfailed = secondddstatusfailed;
  }

  public String getSecondddstatussucceeded() {
    return this.secondddstatussucceeded;
  }

  public void setSecondddstatussucceeded(String secondddstatussucceeded) {
    this.secondddstatussucceeded = secondddstatussucceeded;
  }

  public Date getSecondddstatusdate() {
    return this.secondddstatusdate;
  }

  public void setSecondddstatusdate(Date secondddstatusdate) {
    this.secondddstatusdate = secondddstatusdate;
  }

  public String getIsbpay() {
    return this.isbpay;
  }

  public void setIsbpay(String isbpay) {
    this.isbpay = isbpay;
  }

  public String getBpayreference() {
    return this.bpayreference;
  }

  public void setBpayreference(String bpayreference) {
    this.bpayreference = bpayreference;
  }

  public String getBpaystatusfailed() {
    return this.bpaystatusfailed;
  }

  public void setBpaystatusfailed(String bpaystatusfailed) {
    this.bpaystatusfailed = bpaystatusfailed;
  }

  public String getBpaystatussucceeded() {
    return this.bpaystatussucceeded;
  }

  public void setBpaystatussucceeded(String bpaystatussucceeded) {
    this.bpaystatussucceeded = bpaystatussucceeded;
  }

  public Date getBpaystatusdate() {
    return this.bpaystatusdate;
  }

  public void setBpaystatusdate(Date bpaystatusdate) {
    this.bpaystatusdate = bpaystatusdate;
  }

  public String getIsdirectcredit() {
    return this.isdirectcredit;
  }

  public void setIsdirectcredit(String isdirectcredit) {
    this.isdirectcredit = isdirectcredit;
  }

  public String getDirectcreditstatusfailed() {
    return this.directcreditstatusfailed;
  }

  public void setDirectcreditstatusfailed(String directcreditstatusfailed) {
    this.directcreditstatusfailed = directcreditstatusfailed;
  }

  public String getDirectcreditstatussucceeded() {
    return this.directcreditstatussucceeded;
  }

  public void setDirectcreditstatussucceeded(String directcreditstatussucceeded) {
    this.directcreditstatussucceeded = directcreditstatussucceeded;
  }

  public Date getDirectcreditstatusdate() {
    return this.directcreditstatusdate;
  }

  public void setDirectcreditstatusdate(Date directcreditstatusdate) {
    this.directcreditstatusdate = directcreditstatusdate;
  }

  public Date getChequebankeddate() {
    return this.chequebankeddate;
  }

  public void setChequebankeddate(Date chequebankeddate) {
    this.chequebankeddate = chequebankeddate;
  }

  public String getOpsissueraisedticked() {
    return this.opsissueraisedticked;
  }

  public void setOpsissueraisedticked(String opsissueraisedticked) {
    this.opsissueraisedticked = opsissueraisedticked;
  }

  public Date getOpsissueraiseddate() {
    return this.opsissueraiseddate;
  }

  public void setOpsissueraiseddate(Date opsissueraiseddate) {
    this.opsissueraiseddate = opsissueraiseddate;
  }

  public String getOpsissueraiseduserid() {
    return this.opsissueraiseduserid;
  }

  public void setOpsissueraiseduserid(String opsissueraiseduserid) {
    this.opsissueraiseduserid = opsissueraiseduserid;
  }

  public String getOpsissueresolvedticked() {
    return this.opsissueresolvedticked;
  }

  public void setOpsissueresolvedticked(String opsissueresolvedticked) {
    this.opsissueresolvedticked = opsissueresolvedticked;
  }

  public Date getOpsissueresolveddate() {
    return this.opsissueresolveddate;
  }

  public void setOpsissueresolveddate(Date opsissueresolveddate) {
    this.opsissueresolveddate = opsissueresolveddate;
  }

  public String getOpsissueresolveduserid() {
    return this.opsissueresolveduserid;
  }

  public void setOpsissueresolveduserid(String opsissueresolveduserid) {
    this.opsissueresolveduserid = opsissueresolveduserid;
  }

  public String getOperationscomments1() {
    return this.operationscomments1;
  }

  public void setOperationscomments1(String operationscomments1) {
    this.operationscomments1 = operationscomments1;
  }

  public String getOperationscomments2() {
    return this.operationscomments2;
  }

  public void setOperationscomments2(String operationscomments2) {
    this.operationscomments2 = operationscomments2;
  }

  public String getOperationscomments3() {
    return this.operationscomments3;
  }

  public void setOperationscomments3(String operationscomments3) {
    this.operationscomments3 = operationscomments3;
  }

  public String getOperationscomments4() {
    return this.operationscomments4;
  }

  public void setOperationscomments4(String operationscomments4) {
    this.operationscomments4 = operationscomments4;
  }

  public String getOperationscomments5() {
    return this.operationscomments5;
  }

  public void setOperationscomments5(String operationscomments5) {
    this.operationscomments5 = operationscomments5;
  }

  public String getOperationscomments6() {
    return this.operationscomments6;
  }

  public void setOperationscomments6(String operationscomments6) {
    this.operationscomments6 = operationscomments6;
  }

  public String getOperationscomments7() {
    return this.operationscomments7;
  }

  public void setOperationscomments7(String operationscomments7) {
    this.operationscomments7 = operationscomments7;
  }

  public String getOperationscomments8() {
    return this.operationscomments8;
  }

  public void setOperationscomments8(String operationscomments8) {
    this.operationscomments8 = operationscomments8;
  }

  public String getOperationscomments9() {
    return this.operationscomments9;
  }

  public void setOperationscomments9(String operationscomments9) {
    this.operationscomments9 = operationscomments9;
  }

  public Date getOnboardinglastmodifieddate() {
    return this.onboardinglastmodifieddate;
  }

  public void setOnboardinglastmodifieddate(Date onboardinglastmodifieddate) {
    this.onboardinglastmodifieddate = onboardinglastmodifieddate;
  }

  public Date getCreditlastmodifieddate() {
    return this.creditlastmodifieddate;
  }

  public void setCreditlastmodifieddate(Date creditlastmodifieddate) {
    this.creditlastmodifieddate = creditlastmodifieddate;
  }

  public Date getAmllastmodifieddate() {
    return this.amllastmodifieddate;
  }

  public void setAmllastmodifieddate(Date amllastmodifieddate) {
    this.amllastmodifieddate = amllastmodifieddate;
  }

  public String getOperationslastuser() {
    return this.operationslastuser;
  }

  public void setOperationslastuser(String operationslastuser) {
    this.operationslastuser = operationslastuser;
  }

  public Date getOperationslastmodifieddate() {
    return this.operationslastmodifieddate;
  }

  public void setOperationslastmodifieddate(Date operationslastmodifieddate) {
    this.operationslastmodifieddate = operationslastmodifieddate;
  }

  public String getAdministrationlastuser() {
    return this.administrationlastuser;
  }

  public void setAdministrationlastuser(String administrationlastuser) {
    this.administrationlastuser = administrationlastuser;
  }

  public Date getAdministrationlastmodifieddate() {
    return this.administrationlastmodifieddate;
  }

  public void setAdministrationlastmodifieddate(Date administrationlastmodifieddate) {
    this.administrationlastmodifieddate = administrationlastmodifieddate;
  }

  public String getMasterlastuser() {
    return this.masterlastuser;
  }

  public void setMasterlastuser(String masterlastuser) {
    this.masterlastuser = masterlastuser;
  }

  public Date getMasterlastmodifieddate() {
    return this.masterlastmodifieddate;
  }

  public void setMasterlastmodifieddate(Date masterlastmodifieddate) {
    this.masterlastmodifieddate = masterlastmodifieddate;
  }

  public String getAdviserbonafideschecked() {
    return this.adviserbonafideschecked;
  }

  public void setAdviserbonafideschecked(String adviserbonafideschecked) {
    this.adviserbonafideschecked = adviserbonafideschecked;
  }

  public String getAutomaticdirectdebitsuppressed() {
    return this.automaticdirectdebitsuppressed;
  }

  public void setAutomaticdirectdebitsuppressed(String automaticdirectdebitsuppressed) {
    this.automaticdirectdebitsuppressed = automaticdirectdebitsuppressed;
  }

  public Set<Investorindividual> getInvestorindividuals() {
    return this.investorindividuals;
  }

  // added by paulmac
  public Investorindividual[] getInvestorindividualsarray() {
    return (Investorindividual[]) this.investorindividuals.toArray(
      new Investorindividual[0]);
  }

  public void setInvestorindividuals(Set<Investorindividual> investorindividuals) {
    this.investorindividuals = investorindividuals; // tmp;
  }

  public void addInvestorindividual(Investorindividual investorindividual) {
    if (this.investorindividuals == null) {
      this.investorindividuals = new TreeSet<Investorindividual>(new InvestorindividualComp());
    }

    this.investorindividuals.add(investorindividual);
    investorindividual.setApplication(this);
  }

  public boolean getIsClone() {
    return (this.investor1label.equals(Constants.INDIVIDUAL) ||
           this.investor1label.equals(Constants.DIRECTOR));
  }

  public SortedSet getBeneficiaries() {
    return this.beneficiaries;
  }

  public SortedSet getApplicants() {
    return this.applicants;
  }

  public Long getTotalamount() {
    return new Long(
      applicationamount01 + applicationamount02 + applicationamount03).longValue();
  }

  public String getDisplaystatus() {
    return Utils.getAppstatus().get(new Long(this.status));
  }

  private int getBusinessday(int dayOfWeek, int dayOfYear) {
    if (dayOfWeek == Calendar.SATURDAY)
      return dayOfYear + 2;
    else if (dayOfWeek == Calendar.SUNDAY)
      return dayOfYear + 1;
    else
      return dayOfYear;
  }

  public String getDisplaypaymentstatus() {
    if (this.getScheduleddddate() == null)
      return Constants.PAY_STATE_PENDING;
    else {
      boolean hasIssue =
        this.getOpsissueraisedticked().equals(Constants.TRUE) &&
        this.getOpsissueresolvedticked().equals(Constants.FALSE);

      boolean eftOk = false;

      if (this.getFirstddstatussucceeded().equals(Constants.TRUE) ||
          this.getSecondddstatussucceeded().equals(Constants.TRUE) ||
          this.getBpaystatussucceeded().equals(Constants.TRUE) ||
          this.getDirectcreditstatussucceeded().equals(Constants.TRUE))
        eftOk = true;

      Calendar calendar = new GregorianCalendar();
      calendar.setTime(new Date());

      int nowDayOfWeek = calendar.get(Calendar.DAY_OF_WEEK);
      int nowDayofYear = calendar.get(Calendar.DAY_OF_YEAR); // delay due to 'Link' retardadation
      Calendar sdddCalendar = new GregorianCalendar();
      sdddCalendar.setTime(this.getScheduleddddate());

      int sddreplydayofyear = sdddCalendar.get(Calendar.DAY_OF_YEAR) + 3; // add 3 day delay for reply to arrive
      int sdddayofweek = sdddCalendar.get(Calendar.DAY_OF_WEEK);
      int sddreplydayofweek =
        (sdddayofweek > 4) ? (sdddayofweek - 4) : (sdddayofweek + 3);

      if (this.getBusinessday(nowDayOfWeek, nowDayofYear) < this.getBusinessday(
        sddreplydayofweek,
        sddreplydayofyear))
        return Constants.PAY_STATE_SCHEDULED;
      else if (eftOk && !hasIssue)
        return Constants.PAY_STATE_PAID;
      else
        return Constants.PAY_STATE_QUERY;
    }
  }

  public Long getApplicationamount01() {
    return new Long(applicationamount01).longValue();
  }

  public void setApplicationamount01(Long applicationamount01) {
    this.applicationamount01 = new Long(applicationamount01).longValue();
  }

  public Long getApplicationamount02() {
    return new Long(applicationamount02).longValue();
  }

  public void setApplicationamount02(Long applicationamount02) {
    this.applicationamount02 = new Long(applicationamount02).longValue();
  }

  public Long getApplicationamount03() {
    return new Long(applicationamount03).longValue();
  }

  public void setApplicationamount03(Long applicationamount03) {
    this.applicationamount03 = new Long(applicationamount03).longValue();
  }

  public Long getApplicationamount04() {
    return new Long(applicationamount04).longValue();
  }

  public void setApplicationamount04(Long applicationamount04) {
    this.applicationamount04 = new Long(applicationamount04).longValue();
  }

  public Long getApplicationamount05() {
    return new Long(applicationamount05).longValue();
  }

  public void setApplicationamount05(Long applicationamount05) {
    this.applicationamount05 = new Long(applicationamount05).longValue();
  }

  public String getIstrust() {
    if (Constants.CORPORATE_TRUST_TYPE.equals(new Long(this.getType())) ||
        Constants.PRIVATE_TRUST_TYPE.equals(new Long(this.getType())))
      return Constants.TRUE;
    else
      return Constants.FALSE;
  }

  public boolean getIsapplicantidentified() {
    return applicantidentified;
  }

  public boolean isApplicantidentified() {
    return applicantidentified;
  }

  public void setApplicantidentified(boolean applicantidentified) {
    this.applicantidentified = applicantidentified;
  }

  public boolean getIsdeclarationunderstood() {
    return declarationunderstood;
  }

  public boolean isDeclarationunderstood() {
    return declarationunderstood;
  }

  public void setDeclarationunderstood(boolean declarationunderstood) {
    this.declarationunderstood = declarationunderstood;
  }

  public boolean getIssubmitted() {
    return submitted;
  }

  public boolean isSubmitted() {
    return submitted;
  }

  public void setSubmitted(boolean submitted) {
    this.submitted = submitted;
  }

  public Investorindividual getBeneficiary() {
    return beneficiary;
  }

  public void setBeneficiary(Investorindividual beneficiary) {
    this.beneficiary = beneficiary;
  }

  public void setBeneficiaries(SortedSet<Investorindividual> beneficiaries) {
    this.beneficiaries = beneficiaries;
  }

  public void setApplicants(SortedSet<Investorindividual> applicants) {
    this.applicants = applicants;
  }

  public void addApplicant(Investorindividual applicant) {
    this.applicants.add(applicant);
  }

  public void addBeneficiary(Investorindividual beneficiary) {
    this.beneficiaries.add(beneficiary);
  }

  public long getPaymentmethod() {
    if (this.isborrowingfromubs.equals(Constants.TRUE) &&
        this.isial.equals(Constants.FALSE)) // pay for units with UBS Loan
     {
      return 0;
    } else if (this.isborrowingfromubs.equals(Constants.TRUE) &&
               this.isial.equals(Constants.TRUE)) // pay for units with UBS Loan
     {
      return 1;
    } else if (this.isborrowingfromubs.equals(Constants.FALSE) &&
               this.ispurchasingputfromubs.equals(Constants.TRUE)) // pay for units with UBS Loan
     {
      return 2;
    } else if (this.isborrowingfromubs.equals(Constants.FALSE) &&
               this.ispurchasingputfromubs.equals(Constants.FALSE)) // pay for units with UBS Loan
     {
      return 3;
    } else
      return 0;
  }

  public String getDisplaypaymentmethod() {
    if (this.isborrowingfromubs.equals(Constants.TRUE) &&
        this.isial.equals(Constants.FALSE)) // pay for units with UBS Loan
     {
      return "UBS Loan";
    } else if (this.isborrowingfromubs.equals(Constants.TRUE) &&
               this.isial.equals(Constants.TRUE)) // pay for units with UBS Loan
     {
      return "UBS Interest Loan";
    } else if (this.isborrowingfromubs.equals(Constants.FALSE) &&
               this.ispurchasingputfromubs.equals(Constants.TRUE)) // pay for units with UBS Loan
     {
      return "Direct with Put";
    } else if (this.isborrowingfromubs.equals(Constants.FALSE) &&
               this.ispurchasingputfromubs.equals(Constants.FALSE)) // pay for units with UBS Loan
     {
      return "Direct without Put";
    } else
      return "Undefined!";
  }

  public void setPaymentmethod(long paymentmethod) {
    if (paymentmethod == 0) // pay for units with UBS Loan
     {
      this.isborrowingfromubs = Constants.TRUE;
      this.ispurchasingputfromubs = Constants.TRUE;
      this.isial = Constants.FALSE;
    } else if (paymentmethod == 1) // Buy Units with UBS Loan and Interest Assistance Loan
     {
      this.isborrowingfromubs = Constants.TRUE;
      this.ispurchasingputfromubs = Constants.TRUE;
      this.isial = Constants.TRUE;
    } else if (paymentmethod == 2) // Buy Units and Put Option with my own funds
     {
      this.isborrowingfromubs = Constants.FALSE;
      this.ispurchasingputfromubs = Constants.TRUE;
      this.isial = Constants.FALSE;
    } else // if (paymentmethod == 3) // Buy Units with my own funds (without Put Option)
     {
      this.isborrowingfromubs = Constants.FALSE;
      this.ispurchasingputfromubs = Constants.FALSE;
      this.isial = Constants.FALSE;
    }
  }

  public long getIassetstotal() {
    //return iassetstotal;
    return iassetstotal + icash + ishares + iotherliquid +
           iresidentialproperty + iinvestmentproperty + iotherassets;
  }

  public void setIassetstotal(long iassetstotal) {
    this.iassetstotal = iassetstotal;
  }

  public long getIliabilitiestotal() {
    //return iliabilitiestotal;
    return iliabilitiestotal + iotherloanssecured + iloansresidentialproperty +
           iloansinvestmentproperty + iloanspersonalunsecured +
           iguaranteesgranted + iotherliabilities;
  }

  public void setIliabilitiestotal(long iliabilitiestotal) {
    this.iliabilitiestotal = iliabilitiestotal;
  }

  public long getInettassets() {
    //return inettassets;
    return getIassetstotal() - getIliabilitiestotal();
  }

  public long getIincometotal() {
    //return iincometotal;
    return isalary + irentalanddividend + iotherincome;
  }

  public long getIaftertaxtotal() {
    //return iaftertaxtotal;
    return getIincometotal() - itaxpayable;
  }

  public long getIexpendituretotal() {
    //return iexpendituretotal;
    return iexpendituretotal + iinterestonsecuredloans +
           iinterestonunsecuredloans + ilivingexpenses + iotherexpenses;
  }

  public void setIexpendituretotal(long iexpendituretotal) {
    this.iexpendituretotal = iexpendituretotal;
  }

  public long getIincomeavailable() {
    //return iincomeavailable;
    return getIaftertaxtotal() - getIexpendituretotal();
  }

  public long getGaftertaxtotal() {
    //return gaftertaxtotal;
    return getGincometotal() - gtaxpayable;
  }

  public long getGassetstotal() {
    //return gassetstotal;
    return gcash + gshares + gotherliquid + gresidentialproperty +
           ginvestmentproperty + gotherassets;
  }

  public long getGexpendituretotal() {
    //return gexpendituretotal;
    return ginterestonsecuredloans + ginterestonunsecuredloans +
           glivingexpenses + gotherexpenses;
  }

  public long getGincomeavailable() {
    //return gincomeavailable;
    return getGaftertaxtotal() - getGexpendituretotal();
  }

  public long getGincometotal() {
    //return gincometotal;
    return gsalary + grentalanddividend + gotherincome;
  }

  public long getGliabilitiestotal() {
    //return gliabilitiestotal;
    return gotherloanssecured + gloansresidentialproperty +
           gloansinvestmentproperty + gloanspersonalunsecured +
           gguaranteesgranted + gotherliabilities;
  }

  public long getGnettassets() {
    //return gnettassets;
    return getGassetstotal() - getGliabilitiestotal();
  }

  public long getApplicationamounttotal() {
    return applicationamount01 + applicationamount02 + applicationamount03;
  }

  public String getAmlinfonotyetchecked() {
    return amlinfonotyetchecked;
  }

  public void setAmlinfonotyetchecked(String amlinfonotyetchecked) {
    this.amlinfonotyetchecked = amlinfonotyetchecked;
  }

  public String getAmllock() {
    return amllock;
  }

  public void setAmllock(String amllock) {
    this.amllock = amllock;
  }

  public String getApplicant1approved() {
    return applicant1approved;
  }

  public void setApplicant1approved(String applicant1approved) {
    this.applicant1approved = applicant1approved;
  }

  public String getApplicant1immaterial() {
    return applicant1immaterial;
  }

  public void setApplicant1immaterial(String applicant1immaterial) {
    this.applicant1immaterial = applicant1immaterial;
  }

  public String getApplicant1material() {
    return applicant1material;
  }

  public void setApplicant1material(String applicant1material) {
    this.applicant1material = applicant1material;
  }

  public String getApplicant1nohit() {
    return applicant1nohit;
  }

  public void setApplicant1nohit(String applicant1nohit) {
    this.applicant1nohit = applicant1nohit;
  }

  public String getApplicant1notapplicable() {
    return applicant1notapplicable;
  }

  public void setApplicant1notapplicable(String applicant1notapplicable) {
    this.applicant1notapplicable = applicant1notapplicable;
  }

  public String getApplicant2approved() {
    return applicant2approved;
  }

  public void setApplicant2approved(String applicant2approved) {
    this.applicant2approved = applicant2approved;
  }

  public String getApplicant2immaterial() {
    return applicant2immaterial;
  }

  public void setApplicant2immaterial(String applicant2immaterial) {
    this.applicant2immaterial = applicant2immaterial;
  }

  public String getApplicant2material() {
    return applicant2material;
  }

  public void setApplicant2material(String applicant2material) {
    this.applicant2material = applicant2material;
  }

  public String getApplicant2nohit() {
    return applicant2nohit;
  }

  public void setApplicant2nohit(String applicant2nohit) {
    this.applicant2nohit = applicant2nohit;
  }

  public String getApplicant2notapplicable() {
    return applicant2notapplicable;
  }

  public void setApplicant2notapplicable(String applicant2notapplicable) {
    this.applicant2notapplicable = applicant2notapplicable;
  }

  public String getApplicationdeleted() {
    return applicationdeleted;
  }

  public void setApplicationdeleted(String applicationdeleted) {
    this.applicationdeleted = applicationdeleted;
  }

  public String getApplicationwithdrawn() {
    return applicationwithdrawn;
  }

  public void setApplicationwithdrawn(String applicationwithdrawn) {
    this.applicationwithdrawn = applicationwithdrawn;
  }

  public Date getApprovalnotificationdate() {
    return approvalnotificationdate;
  }

  public void setApprovalnotificationdate(Date approvalnotificationdate) {
    this.approvalnotificationdate = approvalnotificationdate;
  }

  public long getApprovedamount01() {
    return approvedamount01;
  }

  public void setApprovedamount01(long approvedamount01) {
    this.approvedamount01 = approvedamount01;
  }

  public long getApprovedamount02() {
    return approvedamount02;
  }

  public void setApprovedamount02(long approvedamount02) {
    this.approvedamount02 = approvedamount02;
  }

  public long getApprovedamount03() {
    return approvedamount03;
  }

  public void setApprovedamount03(long approvedamount03) {
    this.approvedamount03 = approvedamount03;
  }

  public long getApprovedamount04() {
    return approvedamount04;
  }

  public void setApprovedamount04(long approvedamount04) {
    this.approvedamount04 = approvedamount04;
  }

  public long getApprovedamount05() {
    return approvedamount05;
  }

  public void setApprovedamount05(long approvedamount05) {
    this.approvedamount05 = approvedamount05;
  }

  public String getAsicbeneficiary1check() {
    return asicbeneficiary1check;
  }

  public void setAsicbeneficiary1check(String asicbeneficiary1check) {
    this.asicbeneficiary1check = asicbeneficiary1check;
  }

  public String getAsicbeneficiary2check() {
    return asicbeneficiary2check;
  }

  public void setAsicbeneficiary2check(String asicbeneficiary2check) {
    this.asicbeneficiary2check = asicbeneficiary2check;
  }

  public String getAsiccompanysearch() {
    return asiccompanysearch;
  }

  public void setAsiccompanysearch(String asiccompanysearch) {
    this.asiccompanysearch = asiccompanysearch;
  }

  public String getAsicdirector1check() {
    return asicdirector1check;
  }

  public void setAsicdirector1check(String asicdirector1check) {
    this.asicdirector1check = asicdirector1check;
  }

  public String getAsicdirector2check() {
    return asicdirector2check;
  }

  public void setAsicdirector2check(String asicdirector2check) {
    this.asicdirector2check = asicdirector2check;
  }

  public String getAtoregistration() {
    return atoregistration;
  }

  public void setAtoregistration(String atoregistration) {
    this.atoregistration = atoregistration;
  }

  public String getBaycorp1filecreated() {
    return baycorp1filecreated;
  }

  public void setBaycorp1filecreated(String baycorp1filecreated) {
    this.baycorp1filecreated = baycorp1filecreated;
  }

  public String getBaycorp2filecreated() {
    return baycorp2filecreated;
  }

  public void setBaycorp2filecreated(String baycorp2filecreated) {
    this.baycorp2filecreated = baycorp2filecreated;
  }

  public String getBaycorprecordcreated() {
    return baycorprecordcreated;
  }

  public void setBaycorprecordcreated(String baycorprecordcreated) {
    this.baycorprecordcreated = baycorprecordcreated;
  }

  public String getCompanyapproved() {
    return companyapproved;
  }

  public void setCompanyapproved(String companyapproved) {
    this.companyapproved = companyapproved;
  }

  public String getCompanyimmaterial() {
    return companyimmaterial;
  }

  public void setCompanyimmaterial(String companyimmaterial) {
    this.companyimmaterial = companyimmaterial;
  }

  public String getCompanymaterial() {
    return companymaterial;
  }

  public void setCompanymaterial(String companymaterial) {
    this.companymaterial = companymaterial;
  }

  public String getCompanynohit() {
    return companynohit;
  }

  public void setCompanynohit(String companynohit) {
    this.companynohit = companynohit;
  }

  public String getCompanynotapplicable() {
    return companynotapplicable;
  }

  public void setCompanynotapplicable(String companynotapplicable) {
    this.companynotapplicable = companynotapplicable;
  }

  public Date getConditionalnotificationdate() {
    return conditionalnotificationdate;
  }

  public void setConditionalnotificationdate(Date conditionalnotificationdate) {
    this.conditionalnotificationdate = conditionalnotificationdate;
  }

  public String getCorporatechecksverified() {
    return corporatechecksverified;
  }

  public void setCorporatechecksverified(String corporatechecksverified) {
    this.corporatechecksverified = corporatechecksverified;
  }

  public String getCreditinfonotyetchecked() {
    return creditinfonotyetchecked;
  }

  public void setCreditinfonotyetchecked(String creditinfonotyetchecked) {
    this.creditinfonotyetchecked = creditinfonotyetchecked;
  }

  public String getCreditlock() {
    return creditlock;
  }

  public void setCreditlock(String creditlock) {
    this.creditlock = creditlock;
  }

  public String getGooglecheck1approved() {
    return googlecheck1approved;
  }

  public void setGooglecheck1approved(String googlecheck1approved) {
    this.googlecheck1approved = googlecheck1approved;
  }

  public String getGooglecheck2approved() {
    return googlecheck2approved;
  }

  public void setGooglecheck2approved(String googlecheck2approved) {
    this.googlecheck2approved = googlecheck2approved;
  }

  public String getGridcheck1approved() {
    return gridcheck1approved;
  }

  public void setGridcheck1approved(String gridcheck1approved) {
    this.gridcheck1approved = gridcheck1approved;
  }

  public String getGridcheck2approved() {
    return gridcheck2approved;
  }

  public void setGridcheck2approved(String gridcheck2approved) {
    this.gridcheck2approved = gridcheck2approved;
  }

  public Date getInformationnotificationdate() {
    return informationnotificationdate;
  }

  public void setInformationnotificationdate(Date informationnotificationdate) {
    this.informationnotificationdate = informationnotificationdate;
  }

  public String getMainlock() {
    return mainlock;
  }

  public void setMainlock(String mainlock) {
    this.mainlock = mainlock;
  }

  public Date getNotificationdate() {
    return notificationdate;
  }

  public void setNotificationdate(Date notificationdate) {
    this.notificationdate = notificationdate;
  }

  public String getOnboardinginfonotyetchecked() {
    return onboardinginfonotyetchecked;
  }

  public void setOnboardinginfonotyetchecked(String onboardinginfonotyetchecked) {
    this.onboardinginfonotyetchecked = onboardinginfonotyetchecked;
  }

  public String getOnboardinglock() {
    return onboardinglock;
  }

  public void setOnboardinglock(String onboardinglock) {
    this.onboardinglock = onboardinglock;
  }

  public String getOtherpersonsapproved() {
    return otherpersonsapproved;
  }

  public void setOtherpersonsapproved(String otherpersonsapproved) {
    this.otherpersonsapproved = otherpersonsapproved;
  }

  public String getOtherpersonsimmaterial() {
    return otherpersonsimmaterial;
  }

  public void setOtherpersonsimmaterial(String otherpersonsimmaterial) {
    this.otherpersonsimmaterial = otherpersonsimmaterial;
  }

  public String getOtherpersonsmaterial() {
    return otherpersonsmaterial;
  }

  public void setOtherpersonsmaterial(String otherpersonsmaterial) {
    this.otherpersonsmaterial = otherpersonsmaterial;
  }

  public String getOtherpersonsnohit() {
    return otherpersonsnohit;
  }

  public void setOtherpersonsnohit(String otherpersonsnohit) {
    this.otherpersonsnohit = otherpersonsnohit;
  }

  public String getOtherpersonsnotapplicable() {
    return otherpersonsnotapplicable;
  }

  public void setOtherpersonsnotapplicable(String otherpersonsnotapplicable) {
    this.otherpersonsnotapplicable = otherpersonsnotapplicable;
  }

  public Date getRecordCreated() {
    return recordCreated;
  }

  public void setRecordCreated(Date recordCreated) {
    this.recordCreated = recordCreated;
  }

  public String getSuperfundregistrationcheck() {
    return superfundregistrationcheck;
  }

  public void setSuperfundregistrationcheck(String superfundregistrationcheck) {
    this.superfundregistrationcheck = superfundregistrationcheck;
  }

  public String getTrustdeedapproved() {
    return trustdeedapproved;
  }

  public void setTrustdeedapproved(String trustdeedapproved) {
    this.trustdeedapproved = trustdeedapproved;
  }

  public String getWorldcheck1approved() {
    return worldcheck1approved;
  }

  public void setWorldcheck1approved(String worldcheck1approved) {
    this.worldcheck1approved = worldcheck1approved;
  }

  public String getWorldcheck2approved() {
    return worldcheck2approved;
  }

  public void setWorldcheck2approved(String worldcheck2approved) {
    this.worldcheck2approved = worldcheck2approved;
  }

  public void setApplicationamount01(long applicationamount01) {
    this.applicationamount01 = applicationamount01;
  }

  public void setApplicationamount02(long applicationamount02) {
    this.applicationamount02 = applicationamount02;
  }

  public void setApplicationamount03(long applicationamount03) {
    this.applicationamount03 = applicationamount03;
  }

  public void setApplicationamount04(long applicationamount04) {
    this.applicationamount04 = applicationamount04;
  }

  public void setApplicationamount05(long applicationamount05) {
    this.applicationamount05 = applicationamount05;
  }

  public long getApprovedamount() {
    approvedamount += (this.approvedamount01 + this.approvedamount02 +
                      this.approvedamount03 + this.approvedamount04 +
                      this.approvedamount05);

    if (this.isStatusapproved())
      return approvedamount;
    else
      return 0;
  }

  public void setApprovedamount(long approvedamount) {
    this.approvedamount = approvedamount;
  }

  public long getBeneficiaryindex() {
    return ++beneficiaryindex;
  }

  public void setBeneficiaryindex(long beneficiaryindex) {
    this.beneficiaryindex = beneficiaryindex;
  }

  public Date getRecordModified() {
    return recordModified;
  }

  public void setRecordModified(Date recordModified) {
    this.recordModified = recordModified;
  }

  public long getApplicantindex() {
    return ++applicantindex;
  }

  public void setApplicantindex(long applicantindex) {
    this.applicantindex = applicantindex;
  }

  public Application getTemplate() {
    return template;
  }

  public void setTemplate(Application template) {
    this.template = template;
  }

  public String getDdAccountType() {
    return this.ddAccountType;
  }

  public void setDdAccountType(String ddAccountType) {
    this.ddAccountType = ddAccountType;
  }

  public ApplicationDirectCreditDetails getDirectCreditDetails() {
    return this.directCreditDetails;
  }

  public void setDirectCreditDetails(ApplicationDirectCreditDetails directCreditDetails) {
    this.directCreditDetails = directCreditDetails;
  }

  //~ Static fields/initializers -----------------------------------------------

  private static final Log log = LogFactory.getLog(Application.class);

  //~ Instance fields ----------------------------------------------------------

  private Investorindividual beneficiary; // holds a transient Individual
  private String investor1label;
  private boolean declarationunderstood = false;
  private boolean applicantidentified = false;
  private boolean submitted = false;
  private long iassetstotal = 0;
  private long iliabilitiestotal = 0;
  private long iexpendituretotal = 0;
  private long approvedamount = 0;
  private long beneficiaryindex = 0;
  private long applicantindex = 0;
  private Application template;
  private long id = Constants.NEW_DOMAIN_ID; // mod. by paulmac
  private Company company;
  private Advisor advisor;
  private Product product;
  private Trust trust;
  private double commission;
  private String applicationnumber;
  private String clientnumber;
  private String accountdesignation;
  private String firstname;
  private String middlename;
  private String lastname;
  private String homephone;
  private String workphone;
  private String email;
  private String fax;
  private String address1;
  private String address2;
  private String suburb;
  private String state;
  private String postcode;
  private String country;
  private long type;
  private long applicationamount01;
  private long applicationamount02;
  private long applicationamount03;
  private long applicationamount04;
  private long applicationamount05;
  private long approvedamount01;
  private long approvedamount02;
  private long approvedamount03;
  private long approvedamount04;
  private long approvedamount05;
  private Date recordCreated;
  private long status;
  private long paymentstatus;
  private String isborrowingfromubs = Constants.FALSE;
  private String ispurchasingputfromubs = Constants.FALSE;
  private String isial = Constants.FALSE;
  private String iseithertosign = Constants.FALSE;
  private String ispapercopywanted = Constants.FALSE;
  private String isprovidercustomer = Constants.FALSE;
  private String islatest = Constants.TRUE;
  private String reinvestdistribution = Constants.FALSE;
  private String directcreditdistribution = Constants.FALSE;
  private String providerunitholdernumber;
  private String providerfundname;
  private String isubscustomer = Constants.FALSE;
  private String ubsunitholdernumber;
  private String ubsfundname;
  private String ddapplicant;
  private String ddabn;
  private String ddinstitution;
  private String ddinstitutionaddress;
  private String ddinstitutionpostcode;
  private String ddinstitutionstate;
  private String ddinstitutionsuburb;
  private String ddaccountname;
  private String ddbsb;
  private String ddaccountno;
  private String ddAccountType;
  private long icash;
  private long ishares;
  private long iotherliquid;
  private long iresidentialproperty;
  private long iinvestmentproperty;
  private long iotherassets;
  private String iotherassetsdetails;
  private long iotherloanssecured;
  private long iloansresidentialproperty;
  private long iloansinvestmentproperty;
  private long iloanspersonalunsecured;
  private long iguaranteesgranted;
  private long iotherliabilities;
  private String iotherliabilitiesdetails;
  private long isalary;
  private long irentalanddividend;
  private long iotherincome;
  private String iotherincomedetails;
  private long itaxpayable;
  private Date itaxpayabledate;
  private long iinterestonsecuredloans;
  private long iinterestonunsecuredloans;
  private long ilivingexpenses;
  private long iotherexpenses;
  private String iotherexpensesdetails;
  private long gcash;
  private long gshares;
  private long gotherliquid;
  private long gresidentialproperty;
  private long ginvestmentproperty;
  private long gotherassets;
  private String gotherassetsdetails;
  private long gotherloanssecured;
  private long gloansresidentialproperty;
  private long gloansinvestmentproperty;
  private long gloanspersonalunsecured;
  private long gguaranteesgranted;
  private long gotherliabilities;
  private String gotherliabilitiesdetails;
  private long gsalary;
  private long grentalanddividend;
  private long gotherincome;
  private String gotherincomedetails;
  private long gtaxpayable;
  private Date gtaxpayabledate;
  private long ginterestonsecuredloans;
  private long ginterestonunsecuredloans;
  private long glivingexpenses;
  private long gotherexpenses;
  private String gotherexpensesdetails;
  private long onboardingstatus;
  private String onboardinglastuser;
  private String onboardingcomments;
  private String onboardinghardcopysighted = Constants.FALSE;
  private String dadealergroup = Constants.FALSE;
  private long creditstatus;
  private String creditlastuser;
  private String creditcomments;
  private String casapproved = Constants.FALSE;
  private String baycorpsapproved = Constants.FALSE;
  private long amlstatus;
  private String amllastuser;
  private String amlcomments;
  private String amlhardcopysighted = Constants.FALSE;
  private String creditcheckverified = Constants.FALSE;
  private String gridcheckverified = Constants.FALSE;
  private String worldcheckverified = Constants.FALSE;
  private String googlecheckverified = Constants.FALSE;
  private String corporatechecksverified = Constants.FALSE;
  private String trustchecksverified = Constants.FALSE;
  private String operationscomments;
  private long bank3rdpartyauthorisation;
  private String billingapproved = Constants.FALSE;
  private String reconciledbillingdata = Constants.FALSE;
  private String generatedbillingdata = Constants.FALSE;
  private String amountduepaid;
  private Date scheduleddddate;
  private String ddpaymentsuccessful = Constants.FALSE;
  private String ddunsuccessfulreason;
  private String initialpaymentbycheque = Constants.FALSE;
  private double paymentbyalternativemeans;
  private String conductedbilling = Constants.FALSE;
  private String generatedapprovalletter = Constants.FALSE;
  private String generatedrejectionletter = Constants.FALSE;
  private String administrationcomments;
  private String onboardinginfo1satisfied = Constants.FALSE;
  private String onboardinginfo1commentary;
  private String onboardinginfo2satisfied = Constants.FALSE;
  private String onboardinginfo2commentary;
  private String onboardinginfo3satisfied = Constants.FALSE;
  private String onboardinginfo3commentary;
  private String creditinfo1satisfied = Constants.FALSE;
  private String creditinfo1commentary;
  private String creditinfo2satisfied = Constants.FALSE;
  private String creditinfo2commentary;
  private String creditinfo3satisfied = Constants.FALSE;
  private String creditinfo3commentary;
  private String amlinfo1satisfied = Constants.FALSE;
  private String amlinfo1commentary;
  private String amlinfo2satisfied = Constants.FALSE;
  private String amlinfo2commentary;
  private String amlinfo3satisfied = Constants.FALSE;
  private String amlinfo3commentary;
  private String onboardinginfonotyetchecked = Constants.FALSE;
  private String creditinfonotyetchecked = Constants.FALSE;
  private String amlinfonotyetchecked = Constants.FALSE;
  private String baycorprecordcreated = Constants.FALSE;
  private String asiccompanysearch = Constants.FALSE;
  private String atoregistration = Constants.FALSE;
  private String trustdeedapproved = Constants.FALSE;
  private String applicant1approved = Constants.FALSE;
  private String applicant1material = Constants.FALSE;
  private String applicant1immaterial = Constants.FALSE;
  private String applicant1nohit = Constants.FALSE;
  private String applicant1notapplicable = Constants.FALSE;
  private String applicant2approved = Constants.FALSE;
  private String applicant2material = Constants.FALSE;
  private String applicant2immaterial = Constants.FALSE;
  private String applicant2nohit = Constants.FALSE;
  private String applicant2notapplicable = Constants.FALSE;
  private String companyapproved = Constants.FALSE;
  private String companymaterial = Constants.FALSE;
  private String companyimmaterial = Constants.FALSE;
  private String companynohit = Constants.FALSE;
  private String companynotapplicable = Constants.FALSE;
  private String otherpersonsapproved = Constants.FALSE;
  private String otherpersonsmaterial = Constants.FALSE;
  private String otherpersonsimmaterial = Constants.FALSE;
  private String otherpersonsnohit = Constants.FALSE;
  private String otherpersonsnotapplicable = Constants.FALSE;
  private Date informationnotificationdate;
  private Date conditionalnotificationdate;
  private Date approvalnotificationdate;
  private String applicationwithdrawn = Constants.FALSE;
  private String applicationdeleted = Constants.FALSE;
  private String baycorp1filecreated = Constants.FALSE;
  private String gridcheck1approved = Constants.FALSE;
  private String worldcheck1approved = Constants.FALSE;
  private String googlecheck1approved = Constants.FALSE;
  private String asicdirector1check = Constants.FALSE;
  private String asicbeneficiary1check = Constants.FALSE;
  private String baycorp2filecreated = Constants.FALSE;
  private String gridcheck2approved = Constants.FALSE;
  private String worldcheck2approved = Constants.FALSE;
  private String googlecheck2approved = Constants.FALSE;
  private String asicdirector2check = Constants.FALSE;
  private String asicbeneficiary2check = Constants.FALSE;
  private String superfundregistrationcheck = Constants.FALSE;
  private Date notificationdate;
  private String onboardinglock;
  private String creditlock;
  private String amllock;
  private String mainlock;
  private Date applicationdate;
  private String createdby;
  private String modifiedby;
  private Date recordModified; // modified by paulmac
  private Date softcopyreceiveddate;
  private String chequeforubsattached = Constants.FALSE;
  private String chequereturned = Constants.FALSE;
  private String chequeaccepted = Constants.FALSE;
  private String isreferredtocrc = Constants.FALSE;
  private String firstddstatusfailed = Constants.FALSE;
  private String firstddstatussucceeded = Constants.FALSE;
  private Date firstddstatusdate;
  private String isseconddd = Constants.FALSE;
  private Date secondscheduleddddate;
  private String secondddstatusfailed = Constants.FALSE;
  private String secondddstatussucceeded = Constants.FALSE;
  private Date secondddstatusdate;
  private String isbpay = Constants.FALSE;
  private String bpayreference;
  private String bpaystatusfailed = Constants.FALSE;
  private String bpaystatussucceeded = Constants.FALSE;
  private Date bpaystatusdate;
  private String isdirectcredit = Constants.FALSE;
  private String directcreditstatusfailed = Constants.FALSE;
  private String directcreditstatussucceeded = Constants.FALSE;
  private Date directcreditstatusdate;
  private Date chequebankeddate;
  private String opsissueraisedticked = Constants.FALSE;
  private Date opsissueraiseddate;
  private String opsissueraiseduserid;
  private String opsissueresolvedticked = Constants.FALSE;
  private Date opsissueresolveddate;
  private String opsissueresolveduserid;
  private String operationscomments1;
  private String operationscomments2;
  private String operationscomments3;
  private String operationscomments4;
  private String operationscomments5;
  private String operationscomments6;
  private String operationscomments7;
  private String operationscomments8;
  private String operationscomments9;
  private Date onboardinglastmodifieddate;
  private Date creditlastmodifieddate;
  private Date amllastmodifieddate;
  private String operationslastuser;
  private Date operationslastmodifieddate;
  private String administrationlastuser;
  private Date administrationlastmodifieddate;
  private String masterlastuser;
  private Date masterlastmodifieddate;
  private String adviserbonafideschecked = Constants.FALSE;
  private String automaticdirectdebitsuppressed = Constants.FALSE;
  private ApplicationDirectCreditDetails directCreditDetails;
  private Set<Investorindividual> investorindividuals;
  private SortedSet<Investorindividual> beneficiaries;
  private SortedSet<Investorindividual> applicants;
  boolean statusapproved = false;
}
