package com.ubs.opi.domain;

import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Vector;


/**
 * Company generated by MyEclipse - Hibernate Tools
 */

public class Company extends com.ubs.opi.domain.BaseDomain implements java.io.Serializable {

   static final long serialVersionUID = 3;
   // Fields

    private long id = Constants.NEW_DOMAIN_ID; // mod. by paulmac
     private String type;
     private String name;
     private String tradingname;
     private String address1;
     private String address2;
     private String suburb;
     private String state;
     private String postcode;
     private String telephone;
     private String tfn;
     private String abn;
     private String acn;
     private String arbn;
     private String incorporationcountry;
     private Date incorporationdate;
     private Set dealergroups = new HashSet(0);
     private Set<Product> products = new HashSet<Product>(0);
     private Set applications = new HashSet(0);
     private Set trustsForCompanyid = new HashSet(0);
     private Set<Advisorprovider> advisorproviders = new TreeSet<Advisorprovider>(new AdvisorproviderComp());
     private Set trustsForSolicitorcompanyid = new HashSet(0);
     private Set advisorfirms = new HashSet(0);

     // start added by Paulmac
     private String transbdmid;

     public String getTransbdmid()
   {
      return transbdmid;
   }

   public void setTransbdmid(String transbdmid)
   {
      this.transbdmid = transbdmid;
   }

   public Company(long id) {
        this.id = id;
     }     
     // end added by Paulmac
     
    /** default constructor */
    public Company() {
    }

    /** full constructor */
    public Company(String type, String name, String tradingname, String address1, String address2, String suburb, String state, String postcode, String telephone, String tfn, String abn, String acn, String arbn, String incorporationcountry, Date incorporationdate, Set dealergroups, Set<Product> products, Set applications, Set trustsForCompanyid, Set<Advisorprovider> advisorproviders, Set trustsForSolicitorcompanyid, Set advisorfirms) {
        this.type = type;
        this.name = name;
        this.tradingname = tradingname;
        this.address1 = address1;
        this.address2 = address2;
        this.suburb = suburb;
        this.state = state;
        this.postcode = postcode;
        this.telephone = telephone;
        this.tfn = tfn;
        this.abn = abn;
        this.acn = acn;
        this.arbn = arbn;
        this.incorporationcountry = incorporationcountry;
        this.incorporationdate = incorporationdate;
        this.dealergroups = dealergroups;
        this.products = products;
        this.applications = applications;
        this.trustsForCompanyid = trustsForCompanyid;
        this.advisorproviders = advisorproviders;
        this.trustsForSolicitorcompanyid = trustsForSolicitorcompanyid;
        this.advisorfirms = advisorfirms;
    }

    // added by Paulmac
    public Company clone(long id) {
       Company clone = new Company(id);
       clone.type = type;
       clone.name = name;
       clone.tradingname = tradingname;
       clone.address1 = address1;
       clone.address2 = address2;
       clone.suburb = suburb;
       clone.state = state;
       clone.postcode = postcode;
       clone.telephone = telephone;
       clone.tfn = tfn;
       clone.abn = abn;
       clone.acn = acn;
       clone.arbn = arbn;
       clone.incorporationcountry = incorporationcountry;
       clone.incorporationdate = incorporationdate;
       clone.dealergroups = dealergroups;
       clone.products = products;
//       clone.applications = applications;
//       clone.trustsForCompanyid = trustsForCompanyid;
       clone.advisorproviders = advisorproviders;
//       clone.trustsForSolicitorcompanyid = trustsForSolicitorcompanyid;
       clone.advisorfirms = advisorfirms;
       return clone;
   }

    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTradingname() {
        return this.tradingname;
    }

    public void setTradingname(String tradingname) {
        this.tradingname = tradingname;
    }

    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getSuburb() {
        return this.suburb;
    }

    public void setSuburb(String suburb) {
        this.suburb = suburb;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getTfn() {
        return this.tfn;
    }

    public void setTfn(String tfn) {
        this.tfn = tfn;
    }

    public String getAbn() {
        return this.abn;
    }

    public void setAbn(String abn) {
        this.abn = abn;
    }

    public String getAcn() {
        return this.acn;
    }

    public void setAcn(String acn) {
        this.acn = acn;
    }

    public String getArbn() {
        return this.arbn;
    }

    public void setArbn(String arbn) {
        this.arbn = arbn;
    }

    public String getIncorporationcountry() {
        return this.incorporationcountry;
    }

    public void setIncorporationcountry(String incorporationcountry) {
        this.incorporationcountry = incorporationcountry;
    }

    public Date getIncorporationdate() {
        return this.incorporationdate;
    }

    public void setIncorporationdate(Date incorporationdate) {
        this.incorporationdate = incorporationdate;
    }

    public Set getDealergroups() {
        return this.dealergroups;
    }

    public void setDealergroups(Set dealergroups) {
        this.dealergroups = dealergroups;
    }

    public Set<Product> getProducts() {
        return this.products;
    }

    public void setProducts(Set<Product> products) {
        this.products = products;
    }

    public Set getApplications() {
        return this.applications;
    }

    public void setApplications(Set applications) {
        this.applications = applications;
    }

    public Set getTrustsForCompanyid() {
        return this.trustsForCompanyid;
    }

    public void setTrustsForCompanyid(Set trustsForCompanyid) {
        this.trustsForCompanyid = trustsForCompanyid;
    }

    public Set<Advisorprovider> getAdvisorproviders() {
        return this.advisorproviders;
    }

    public void setAdvisorproviders(Set<Advisorprovider> advisorproviders) {
        this.advisorproviders = advisorproviders;
    }

    private Advisorprovider[] advisorprovidersarray;
    
    // added by paulmac
    public Advisorprovider[] getAdvisorprovidersarray() {
       if (advisorprovidersarray == null)
          getSetadvisorprovidersarray();
//       Advisorprovider[] tmp = (Advisorprovider[])this.advisorproviders.toArray(new Advisorprovider[0]);
       return advisorprovidersarray;
    }

    public int getSetadvisorprovidersarray() {
       List<Advisorprovider> apList = new Vector<Advisorprovider>(advisorproviders);
       Collections.sort(apList,new AdvisorproviderComp());
       advisorprovidersarray = (Advisorprovider[])apList.toArray(new Advisorprovider[0]);
       return 1;
    }
    
    public void setAdvisorprovidersarray(Advisorprovider[] advisorprovidersarray)
    {
       this.advisorprovidersarray = advisorprovidersarray;
    }

    public int getResetadvisorprovidersarray() {
       advisorprovidersarray = null;
       return 1;
    }

    public Set getTrustsForSolicitorcompanyid() {
        return this.trustsForSolicitorcompanyid;
    }

    public void setTrustsForSolicitorcompanyid(Set trustsForSolicitorcompanyid) {
        this.trustsForSolicitorcompanyid = trustsForSolicitorcompanyid;
    }

    public Set getAdvisorfirms() {
        return this.advisorfirms;
    }

    public void setAdvisorfirms(Set advisorfirms) {
        this.advisorfirms = advisorfirms;
    }
    
    public String toString() {
      return "{company: id=" + this.id + ", name=" + this.name + "}";
    }
}