CREATE TABLE "BANK" (
   "BSB" VARCHAR2(6) NOT NULL PRIMARY KEY,
   "TYPE" VARCHAR2(24),
   "NAME" VARCHAR2(80) NOT NULL,
   "ADDRESS1" VARCHAR2(80) NOT NULL,
   "SUBURB" VARCHAR2(24) NOT NULL,
   "STATE" VARCHAR2(3) NOT NULL,
   "POSTCODE" VARCHAR2(4) NOT NULL,
   "TELEPHONE" VARCHAR2(20)
);