select * from bank order by bsb;
insert into bank (bsb,name,address1,suburb,state,postcode) values ('012003','ANZ Pitt & Hunter Streets','68 Pitt Street','Sydney','NSW','2000');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('012005','ANZ Transaction Processing Support Ctr','111 Parramatta Road','Concord','NSW','2137');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('012006','ANZ King & George Streets','365 George Street','Sydney','NSW','2000');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('012009','ANZ Esanda NSW','20 Smith Street','Parramatta','NSW','2150');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('012010','ANZ Bathurst & Castlereagh Streets','Cnr Bathurst & Castlereagh Streets','Sydney','NSW','2000');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('012016','ANZ Corp Banking Martin Place Region','Level 12, 20 Martin Place','Sydney','NSW','2000');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('012315','ANZ Lane Cove','17 Burns Bay Road','Lane Cove','NSW','2066');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('034362','WBC Waterford Instore','1 King Street','Concord West','NSW','2138');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('037633','WBC Strahan In-Store','1 King Street','Concord West','NSW','2138');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('737633','WBC Straham In-Store','1 King Street','Concord West','NSW','2138');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('122725','BQL Kellyville','Shop 19 Kellyville Plaza','Kellyville','NSW','2155');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('122708','BQL Maroubra Junction','Shop 7 Cnr Maroubra Rd & Anzac Pde','Maroubra','NSW','2035');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('122802','BQL Belconnen','Shop 101 Westfields Benjamin Way','Belconnen','ACT','2617');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('016352','ANZ Ellenbrook','Cnr Pinaster Pde - The Promenade','Ellenbrook','WA','6069');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('015204','ANZ Munno Para','600 Main North Road','Smithfield','SA','5114');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('123614','BQL 1 Queens Road','1 Queens Road','Melbourne','VIC','3004');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('124399','BQL Staff Banking Qld','C/-Network Srvs, Lv18, 259 Queen St','Brisbane','QLD','4000');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('065780','CBA Statewide Surannuation Trust','(NBFI Agency to 062-000)','Sydney','NSW','2000');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('765780','CBA Statewide Surannuation Trust','(NBFI Agency to 062-000)','Sydney','NSW','2000');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('766058','CBA Clarkson Loan & Investment Centre','Shop 67, Ocean Keys Shopping Centre','Clarkson','WA','6030');
insert into bank (bsb,name,address1,suburb,state,postcode) values ('122728','BQL Bondi Junction','Shop 3069 Westfield Shp Centre','Bondi Junction','NSW','2022');
commit;
