select * from advisor where (id > 386) and (id<390);
select * from individual where (id > 385) and (id<390);
select * from application where (id > 1030) and (id<1040);
select * from investorindividual where (id > 1030) and (id<1040);
select * from application where accountdesignation like 'as%';
select * from individual where (id = 1404);
 
select * from dealergroup, company where (dealergroup.companyid = company.id) and (dealergroup.afsl = '309406');  
select * from dealergroup, company where (dealergroup.companyid = company.id) and (dealergroup.id = 1237);  
select * from dealergroup, company where (dealergroup.companyid = company.id) and (company.name like 'Retire%');  
select company.name from dealergroup, company where (dealergroup.companyid = company.id) and (dealergroup.isdaapproved='true');  
select * from dealergroup,advisorfirm,advisor,individual where advisor.individualid=individual.id and individual.lastname='Huggins' and advisor.advisorfirmid = advisorfirm.id and dealergroup.afsl='235819' and dealergroupid = advisorfirm.dealergroupid;
select * from application where advisorid=3853;
select * from application where companyid is null;
--delete from individual where id=742;
--delete from users where username='WalkeA';
--delete from advisor where id=743;
--delete from advisorfirm where id=741;
--delete from company where id=740;
-- delete from dealergroup where id=3349;
--commit;
select * from advisor where id=1651;
select * from users order by username;
select * from company,dealergroup where dealergroup.companyid=company.id and dealergroup.id =3842;
select * from company where name like 'Locum%';
select * from company,advisorfirm where advisorfirm.companyid=company.id and advisorfirm.id =3844;
--delete from company where id=3848;
select * from users where username='RobinJ';
select * from advisorfirm,advisor,individual where advisor.individualid=individual.id and individual.lastname='Simpson' and advisor.advisorfirmid = advisorfirm.id;
select * from advisorfirm,company where advisorfirm.companyid = company.id and advisorfirm.id = 3877;
select * from advisorprovider where advisorid > 3800;
select * from company where name like 'Kilcott%';
select * from dealergroup;
select * from advisorfirm, dealergroup, company where advisorfirm.dealergroupid = dealergroup.id and company.id = advisorfirm.companyid and (dealergroup.afsl = '238429') order by company.name;  
select * from dealergroup, company, advisorfirm where dealergroup.id = advisorfirm.dealergroupid and dealergroup.id = 9338 and (dealergroup.companyid = company.id) order by company.name;  
--update dealergroup set afsl='309643' where id=188;
select * from individual where lastname='Moore' and firstname='Brenban';
select * from advisorprovider,advisorfirm,advisor,individual,company,users where advisorprovider.advisorid = advisor.id and advisor.advisorfirmid = advisorfirm.id and advisor.individualid=individual.id and company.id = advisorfirm.companyid and users.username = individual.username and individual.workemail='wendy.drake@williambucksa.com.au' and advisor.id=825;
select * from advisorprovider,advisorfirm,advisor,individual,company where advisorprovider.advisorid = advisor.id and advisor.advisorfirmid = advisorfirm.id and advisor.individualid=individual.id and company.id = advisorfirm.companyid and individual.id=889;
select * from application where advisorid=1144;
select * from advisorprovider;
select * from advisorfirm,dealergroup,company where dealergroup.id = advisorfirm.dealergroupid and company.id = dealergroup.companyid;
select * from company order by name;
select * from advisorprovider, dealergroup, advisorfirm,advisor,individual,company,users where advisorfirm.dealergroupid = dealergroup.id and advisorprovider.advisorid = advisor.id and advisor.advisorfirmid = advisorfirm.id and advisor.individualid=individual.id and company.id = dealergroup.companyid and users.username = individual.username and individual.lastname='Morcos';
select * from advisorprovider,advisorfirm,advisor,individual,company,users where advisorprovider.advisorid = advisor.id and advisor.advisorfirmid = advisorfirm.id and advisor.individualid=individual.id and company.id = advisorfirm.companyid and users.username = individual.username and advisor.id=9156;
--update application set advisorid=5312 where id=1524;
--update application set advisorid=5312 where id=5039;
--update application set advisorid=5312 where id=8010;
--update application set advisorid=5312 where id=7531;
--update application set advisorid=5312 where id=8909;
--update application set advisorid=5312 where id=10372;
--update application set advisorid=5312 where id=10686;
--update application set advisorid=5312 where id=10621;
--update application set advisorid=5097 where id=4069;
--update dealergroup set isdaapproved='false' where id=1237;
--update advisorfirm set dealergroupid='3718' where id=11246;
--commit;
--update individual set countryofbirth='CANADA' where countryofbirth like 'Canada%';
--update individual set countryofbirth='UNITED KINGDOM' where countryofbirth like 'GBR%';
--update individual set countryofbirth='GERMANY' where countryofbirth like 'Germany%';
--update individual set countryofbirth='HONG KONG' where countryofbirth like 'HKG%';
--update individual set countryofbirth='INDIA' where countryofbirth = 'IND';
--update individual set countryofbirth='INDIA' where countryofbirth = 'India';
--update individual set countryofbirth='IRELAND' where countryofbirth = 'Ireland';
--update individual set countryofbirth='ITALY' where countryofbirth = 'Italy';
--update individual set countryofbirth='MALTA' where countryofbirth = 'Malaysia';
--update individual set countryofbirth='DENMARK' where countryofbirth = 'Denmark';
--update individual set countryofbirth='NEW ZEALAND' where countryofbirth = 'NZL';
--update individual set countryofbirth='NEW ZEALAND' where countryofbirth = 'New Zealand';
--update individual set countryofbirth='PERU' where countryofbirth = 'PER';
--update individual set countryofbirth='POLAND' where countryofbirth = 'POL';
--update individual set countryofbirth='RUSSIAN FEDERATION' where countryofbirth = 'Russia';
--update individual set countryofbirth='SINGAPORE' where countryofbirth = 'Singapore';
--update individual set countryofbirth='SWITZERLAND' where countryofbirth = 'Switzerland';
--update individual set countryofbirth='TURKEY' where countryofbirth = 'Turkey';
--update individual set countryofbirth='INDIA' where countryofbirth = 'Wentworthville';
--update individual set countryofbirth='ZIMBABWE (FORMERLY RHODESIA)' where countryofbirth = 'ZWE';
--update individual set countryofbirth='ZIMBABWE (FORMERLY RHODESIA)' where countryofbirth = 'Zimbabwe';
--commit;
select * from individual order by countryofbirth;
update company set incorporationcountry='AUSTRALIA' where incorporationcountry like '%ustralia%';
update application set country='AUSTRALIA' where country like 'Australia%';
--commit;
select country from application order by country;
select * from company order by incorporationcountry;
select * from application where id=4223;
select * from advisor where id=1323;
select * from application where status=0 order by advisorid;
select * from application where clientnumber='30951';
select * from application where advisorid=1009;
select * from application where accountdesignation like 'Kar%';
select * from investorindividual where applicationid = 6668;
select * from individual where lastname = 'Kelly' and firstname='Justine';
select * from company where id = 3847;
select * from  company where upper(name) = 'CITIBANK';
select * from company where id = 4289;
select * from advisorprovider, company where advisorprovider.providerid = company.id;
update company set type = 'PROVIDER' where id = 4289;
update advisorprovider set providerid = 4289 where providerid = 4294;
--update company set name = 'hfa' where id = 371;
commit;
select * from advisorprovider, company where advisorprovider.providerid = company.id;
select * from individual where firstname='Kapil';
select * from individual where lastname='Hislop';
select * from advisor where assistantname='Kylie Hislop';
select * from individual where length(countryofbirth)=3;
select id,country,nationality,countryofbirth from individual where length(nationality)=3;
select id,country from application where length(country)=3;
select * from company where length(incorporationcountry)=3;
--update application set country='Australia' where country='AAU';
--update individual set country='Australia' where country='AAU';
--update individual set nationality='Australian' where nationality='AAU';
--update company set incorporationcountry='Australia' where incorporationcountry='AAU';
--update individual set nationality='Australian' where nationality='AAA';
--update individual set countryofbirth='VIETNAM' where countryofbirth='VNM';
--update individual set nationality='VIETNAMESE' where nationality='VNM';
--update application set advisorid=2736 where id=848;
--update application set advisorid=2736 where id=918;
--commit;
select * from investorindividual,individual,users where investorindividual.INDIVIDUALID = individual.ID and individual.lastname='Huggins';
select * from investorindividual where applicationid=6669;
select * from individual, advisor, application where application.CREATEDBY is null and application.status not in (0,8) and advisor.id = application.ADVISORID and individual.id = advisor.individualid;
select * from users,individual, advisor, application where application.status = 0 and advisor.id = application.ADVISORID and individual.id = advisor.individualid and users.username=individual.username;
--update application set CREATEDBY = individual.USERNAME from application,advisor,individual where application.CREATEDBY is null and application.status not in (0,8) and advisor.id = application.ADVISORID and individual.id = advisor.individualid;
--update application set CREATEDBY = individual.USERNAME from application,advisor,individual where application.CREATEDBY is null and application.status not in (0,8) and advisor.id = application.ADVISORID and individual.id = advisor.individualid;
--update application a1 set a1.CREATEDBY = (select distinct individual.USERNAME  
--from individual, advisor
--where a1.CREATEDBY is null 
--and a1.status not in (0,8) 
--and advisor.id = a1.ADVISORID 
--and individual.id = advisor.individualid);
--update advisorfirm set dealergroupid=284 where id=8323;
--commit;
select paymentstatus from application order by paymentstatus;
select id,accountdesignation,paymentstatus,status from application where advisorid=519;
select * from advisorprovider,advisorfirm,advisor,individual,company,users where advisorprovider.advisorid = advisor.id and advisor.advisorfirmid = advisorfirm.id and advisor.individualid=individual.id and company.id = advisorfirm.companyid and users.username = individual.username and individual.lastname='Wing' and individual.firstname='Brett';  
select * from advisorprovider,advisorfirm,advisor,individual,company,users where advisorprovider.advisorid = advisor.id and advisor.advisorfirmid = advisorfirm.id and advisor.individualid=individual.id and company.id = advisorfirm.companyid and users.username = individual.username and advisor.id=890;  
select * from advisorfirm, dealergroup, company where advisorfirm.dealergroupid = dealergroup.id and advisorfirm.companyid = company.id and company.abn is not null order by dealergroup.afsl;
select * from advisorfirm, dealergroup, company, advisor, individual where advisorfirm.dealergroupid = dealergroup.id and advisorfirm.companyid = company.id and advisor.advisorfirmid = advisorfirm.id and advisor.individualid = individual.id and company.abn is not null and dealergroup.afsl = '246747';

--update advisorfirm set dealergroupid='3718' where id=11246;
--rollback;
--commit;
--update application set advisorid=1144 where id=11587;
--update application set advisorid=1144 where id=11417;
--update application set advisorid=1144 where id=11596;
--update application set advisorid=1144 where id=11348;
--update application set advisorid=1144 where id=11637;
--update application set advisorid=1144 where id=11381;
--update application set advisorid=1144 where id=12267;
--update application set advisorid=1144 where id=11696;
--update application set advisorid=1144 where id=11362;
--commit;
--update application set advisorid=866 where id=4752;
--update application set advisorid=866 where id=4714;
--update application set advisorid=866 where id=7156;
--commit;
--update application set advisorid=1009 where id=14405;
--commit;  
select count(*) as total from advisor where id not in (select distinct advisorid from application where advisorid is not null) and id=4321; -- 4321 
--select count(*) as total from advisor where id not in (select distinct advisorId from application where advisorid is not null) and id = , 
select * from application where advisorid = 1405;
select * from advisorfirm where dealergroupid=4;
select * from advisorfirm, company where advisorfirm.companyid = company.id and company.name = 'paulmac firm';
select * from advisorfirm order by id;
select * from users where username='flintf';

