create table FinancialInformation(             -- level 6, was 4
    investorindividualid integer references investorindividual on delete set null,
    cash  numeric(22, 0),
    shares numeric(22, 0),
    otherLiquid numeric(22, 0),
    residentialProperty numeric(22, 0),
    investmentProperty numeric(22, 0),
    otherassets numeric(22, 0),
    otherassetsDetails varchar(50),
    otherLoansSecured numeric(22, 0),
    loansResProperty numeric(22, 0),
    loansInvProperty numeric(22, 0),
    loansPersonalUnse numeric(22, 0),
    guaranteesGranted numeric(22, 0),
    otherLiabilities numeric(22, 0),
    otherLiabilitiesDetails varchar(50),
    salary varchar(50),
    rentalAndDividend numeric(22, 0),
    otherIncome numeric(22, 0),
    otherIncomeDetails varchar(50),
    taxPayable numeric(22, 0),
    taxPayableDate date,
    intSecuredLoans numeric(22, 0),
    intUnsecuredLoans numeric(22, 0),
    livingExpenses numeric(22, 0),
    otherExpenses numeric(22, 0),
    otherExpensesDetails varchar(50)
);
