update dealergroup set isdaapproved = 'true' where afsl = '239445';	   
update dealergroup set isdaapproved = 'true' where afsl = '224972';	   
update dealergroup set isdaapproved = 'true' where afsl = '225973';	   
update dealergroup set isdaapproved = 'true' where afsl = '226159';	   
update dealergroup set isdaapproved = 'true' where afsl = '231140';	   
update dealergroup set isdaapproved = 'true' where afsl = '243320';	   
update dealergroup set isdaapproved = 'true' where afsl = '244252';	   
update dealergroup set isdaapproved = 'true' where afsl = '302318';	   
update dealergroup set isdaapproved = 'true' where afsl = '309643';	   
update dealergroup set isdaapproved = 'true' where afsl = '307379';	   
update dealergroup set isdaapproved = 'true' where afsl = '296724';	   
update dealergroup set isdaapproved = 'true' where afsl = '288305';	   
update dealergroup set isdaapproved = 'true' where afsl = '308297';	   
update dealergroup set isdaapproved = 'true' where afsl = '223280';	   
update dealergroup set isdaapproved = 'true' where afsl = '240774';	   
update dealergroup set isdaapproved = 'true' where afsl = '232701';
update dealergroup set isdaapproved = 'true' where afsl = '274917';
commit;	 
