package org.opi.domain;



/**
 * AclPermission generated by MyEclipse - Hibernate Tools
 */

public class AclPermission extends org.opi.domain.BaseDomain implements java.io.Serializable {

   static final long serialVersionUID = 14;

    // Fields

     private long id = Constants.NEW_DOMAIN_ID;
     private AclObjectIdentity aclObjectIdentity;
     private String recipient;
     private long mask;


    // Constructors

    /** default constructor */
    public AclPermission() {
    }


    /** full constructor */
    public AclPermission(AclObjectIdentity aclObjectIdentity, String recipient, long mask) {
        this.aclObjectIdentity = aclObjectIdentity;
        this.recipient = recipient;
        this.mask = mask;
    }


    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public AclObjectIdentity getAclObjectIdentity() {
        return this.aclObjectIdentity;
    }

    public void setAclObjectIdentity(AclObjectIdentity aclObjectIdentity) {
        this.aclObjectIdentity = aclObjectIdentity;
    }

    public String getRecipient() {
        return this.recipient;
    }

    public void setRecipient(String recipient) {
        this.recipient = recipient;
    }

    public long getMask() {
        return this.mask;
    }

    public void setMask(long mask) {
        this.mask = mask;
    }









}