package org.opi.domain;



/**
 * Advisorindividual generated by MyEclipse - Hibernate Tools
 */

public class Advisorindividual extends org.opi.domain.BaseDomain implements java.io.Serializable {

   // added by paulmac
   static final long serialVersionUID = 11;

    // Fields

     private long id = Constants.NEW_DOMAIN_ID;
     private Advisor advisor;
     private Individual individual;


    // Constructors

    /** default constructor */
    public Advisorindividual() {
    }


    /** full constructor */
    public Advisorindividual(Advisor advisor, Individual individual) {
        this.advisor = advisor;
        this.individual = individual;
    }


    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Advisor getAdvisor() {
        return this.advisor;
    }

    public void setAdvisor(Advisor advisor) {
        this.advisor = advisor;
    }

    public Individual getIndividual() {
        return this.individual;
    }

    public void setIndividual(Individual individual) {
        this.individual = individual;
    }









}