package org.opi.domain;



/**
 * Authorities generated by MyEclipse - Hibernate Tools
 */

public class Authorities implements java.io.Serializable {

   // start added by paulmac
   static final long serialVersionUID = 9; // was owned by roles
//   static final public String AdvisorRole = "ROLE_ADVISOR";
//   static final public String AdminRole = "ROLE_ADMINISTRATOR";
   // end added by paulmac

    // Fields

     private AuthoritiesId id;
     private Users users;


    // Constructors

    /** default constructor */
    public Authorities() {
    }


    /** full constructor */
    public Authorities(Users users) {
        this.users = users;
    }


    // Property accessors

    public AuthoritiesId getId() {
        return this.id;
    }

    public void setId(AuthoritiesId id) {
        this.id = id;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }









}