package org.opi.domain;

import java.util.HashSet;
import java.util.Set;


/**
 * Dealergroup generated by MyEclipse - Hibernate Tools
 */

public class Dealergroup extends org.opi.domain.BaseDomain implements java.io.Serializable {

   // added by paulmac
   static final long serialVersionUID = 4;
    // Fields

     private long id = Constants.NEW_DOMAIN_ID; // mod. by paulmac
     private String isdaapproved = Constants.FALSE; // mod. by paulmac
     private Company company;
     private String afsl;
     private String displayabn;
     private String displayname;
     private Set<Advisorfirm> advisorfirms = new HashSet<Advisorfirm>(0);


    // Constructors

    /** default constructor */
    public Dealergroup() {
    }

    public Dealergroup(Company company, String afsl) {
       this.company = company;
       this.afsl = afsl;
    }

    /** full constructor */
    public Dealergroup(Company company, String afsl, String isdaapproved, Set<Advisorfirm> advisorfirms) {
        this.company = company;
        this.afsl = afsl;
        this.isdaapproved = isdaapproved;
        this.advisorfirms = advisorfirms;
    }


    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public String getAfsl() {
       return this.afsl;
   }

   public void setAfsl(String afsl) {
       this.afsl = afsl;
   }
    public Set<Advisorfirm> getAdvisorfirms() {
        return this.advisorfirms;
    }

    public void setAdvisorfirms(Set<Advisorfirm> advisorfirms) {
       this.advisorfirms = advisorfirms;
   }

    public void addAdvisorfirm(Advisorfirm advisorfirm) {
       this.advisorfirms.add(advisorfirm);
       advisorfirm.setDealergroup(this);
    }


   public String getIsdaapproved()
   {
      return isdaapproved;
   }


   public void setIsdaapproved(String isdaapproved)
   {
      if (isdaapproved == null)
         this.isdaapproved = "false";
      else
         this.isdaapproved = isdaapproved;
   }


   public String getDisplayabn() {
      return this.getCompany().getAbn();
   }


   public void setDisplayabn(String displayabn) {
      this.getCompany().setAbn(displayabn);
   }


   public String getDisplayname() {
      return this.getCompany().getName();
   }


   public void setDisplayname(String displayname) {
      this.getCompany().setName(displayname);
   }

//   // added by paulmac
//   public void update(Dwrdealergroup dwrdg) {
//      this.setAfsl(dwrdg.getAfsl());
//      this.setDisplayabn(dwrdg.getAbn());
//      this.setDisplayname(dwrdg.getName());
//      this.setIsdaapproved(dwrdg.getIsdaapproved());
//   }
//   






}