package org.opi.domain;

import java.io.Serializable;

/**
 * Investorindividual generated by MyEclipse - Hibernate Tools
 */
public class Investorindividual implements Serializable, Cloneable {
  //~ Methods ------------------------------------------------------------------
  
  public static enum Type { Beneficiary, Director, Trustee, Applicant, Guarantor };

  public Investorindividual clone() {
    Investorindividual investorindividual = new Investorindividual();

    investorindividual.setRole(role);
    investorindividual.setIsapplicant(isapplicant);
    investorindividual.setIsdirector(isdirector);
    investorindividual.setIsguarantor(isguarantor);
    investorindividual.setIssoledirector(issoledirector);
    investorindividual.setIscompanysecretary(iscompanysecretary);
    investorindividual.setIstrustee(istrustee);
    investorindividual.setIsbeneficiary(isbeneficiary);
    investorindividual.setWealthbyemployment(wealthbyemployment);
    investorindividual.setWealthbyinvestments(wealthbyinvestments);
    investorindividual.setWealthbyother(wealthbyother);
    investorindividual.setWealthbyotherinfo(wealthbyotherinfo);

    Individual clone = individual.clone();
    investorindividual.setIndividual(clone);

    //investorindividual.setIndividual(individual);
    return investorindividual;
  }
  
  public String toString() {
    return "{investorIndividual: id = " + this.id + ", role = " + this.role + "}";
  }
  
  public boolean isNew() {
    return this.id == null;
  }

  public boolean equals(Object o) {
    return o instanceof Investorindividual &&
           (((Investorindividual) o).getId().equals(this.id));
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Application getApplication() {
    return this.application;
  }

  public void setApplication(Application application) {
    this.application = application;
  }

  public Individual getIndividual() {
    return this.individual;
  }

  public void setIndividual(Individual individual) {
    this.individual = individual;
  }

  public FinancialInformation getFinancialInformation() {
    return this.financialInformation;
  }

  public void setFinancialInformation(FinancialInformation financialInformation) {
    this.financialInformation = financialInformation;
  }
  
  public String getRole() {
    return this.role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public String getIsapplicant() {
    return this.isapplicant;
  }

  public void setIsapplicant(String isapplicant) {
    this.isapplicant = isapplicant;
  }

  public String getIsguarantor() {
    return this.isguarantor;
  }

  public void setIsguarantor(String isguarantor) {
    if (isguarantor == null)
      this.isguarantor = Constants.FALSE;
    else
      this.isguarantor = isguarantor;
  }

  public boolean isdirector() {
    return this.isdirector.equals(Constants.TRUE);
  }

  public String getIsdirector() {
    return this.isdirector;
  }

  public void setIsdirector(String isdirector) {
    if (isdirector == null)
      this.isdirector = Constants.FALSE;
    else
      this.isdirector = isdirector;
  }

  public String getIstrustee() {
    return this.istrustee;
  }

  public void setIstrustee(String istrustee) {
    this.istrustee = istrustee;
  }

  public String getIsbeneficiary() {
    return this.isbeneficiary;
  }

  public void setIsbeneficiary(String isbeneficiary) {
    if (isbeneficiary == null)
      this.isbeneficiary = Constants.FALSE;
    else
      this.isbeneficiary = isbeneficiary;
  }

  public String getIscompanysecretary() {
    return iscompanysecretary;
  }

  public void setIscompanysecretary(String iscompanysecretary) {
    if (iscompanysecretary == null)
      this.iscompanysecretary = Constants.FALSE;
    else
      this.iscompanysecretary = iscompanysecretary;
  }

  public String getIssoledirector() {
    return issoledirector;
  }

  public void setIssoledirector(String issoledirector) {
    if (issoledirector == null)
      this.issoledirector = Constants.FALSE;
    else
      this.issoledirector = issoledirector;
  }

  public String getWealthbyemployment() {
    return this.wealthbyemployment;
  }

  public void setWealthbyemployment(String wealthbyemployment) {
    if (wealthbyemployment == null)
      this.wealthbyemployment = "false";
    else
      this.wealthbyemployment = wealthbyemployment;
  }

  public String getWealthbyinvestments() {
    return this.wealthbyinvestments;
  }

  public void setWealthbyinvestments(String wealthbyinvestments) {
    if (wealthbyinvestments == null)
      this.wealthbyinvestments = "false";
    else
      this.wealthbyinvestments = wealthbyinvestments;
  }

  public String getWealthbyother() {
    return this.wealthbyother;
  }

  public void setWealthbyother(String wealthbyother) {
    if (wealthbyother == null)
      this.wealthbyother = "false";
    else
      this.wealthbyother = wealthbyother;
  }

  public String getWealthbyotherinfo() {
    return wealthbyotherinfo;
  }

  public void setWealthbyotherinfo(String wealthbyotherinfo) {
    this.wealthbyotherinfo = wealthbyotherinfo;
  }

  //~ Instance fields ----------------------------------------------------------

  private Long id;
  private Application application;
  private Individual individual;
  private FinancialInformation financialInformation;
  private String role;
  private String isapplicant = Constants.TRUE; // for Company applicant. isApplicant also implies isDirector
  private String isguarantor = Constants.FALSE;
  private String isdirector = Constants.FALSE;
  private String issoledirector = Constants.FALSE;
  private String iscompanysecretary = Constants.FALSE;
  private String istrustee = Constants.FALSE;
  private String isbeneficiary = Constants.FALSE;
  private String wealthbyemployment = Constants.FALSE;
  private String wealthbyinvestments = Constants.FALSE;
  private String wealthbyother = Constants.FALSE;
  private String wealthbyotherinfo;

}
