package org.opi.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

/**
 * Product generated by MyEclipse - Hibernate Tools
 */
public class Product implements Serializable {
  //~ Methods ------------------------------------------------------------------
  public boolean isDirectDebitRequired() {
    return !this.code.equals("citibank1") && !this.code.equals("citibank2");
  }
  
  public boolean isDirectCreditRequired() {
    return !this.code.equals("hfa");
  }

  public void setHasminimumbase(String hasminimumbase) {
    if (hasminimumbase == null)
      this.hasminimumbase = "false";
    else
      this.hasminimumbase = hasminimumbase;
  }

  public void setHasminimumincrement(String hasminimumincrement) {
    if (hasminimumincrement == null)
      this.hasminimumincrement = "false";
    else
      this.hasminimumincrement = hasminimumincrement;
  }
  
  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Company getCompany() {
    return this.company;
  }

  public void setCompany(Company company) {
    this.company = company;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Date getClosingdate() {
    return this.closingdate;
  }

  public void setClosingdate(Date closingdate) {
    this.closingdate = closingdate;
  }

  public String getShortdesc() {
    return this.shortdesc;
  }

  public void setShortdesc(String shortdesc) {
    this.shortdesc = shortdesc;
  }

  public long getLowminimum() {
    return this.lowminimum;
  }

  public void setLowminimum(long lowminimum) {
    this.lowminimum = lowminimum;
  }

  public long getLowincrement() {
    return this.lowincrement;
  }

  public void setLowincrement(long lowincrement) {
    this.lowincrement = lowincrement;
  }

  public long getHighminimum() {
    return this.highminimum;
  }

  public void setHighminimum(long highminimum) {
    this.highminimum = highminimum;
  }

  public long getHighincrement() {
    return this.highincrement;
  }

  public void setHighincrement(long highincrement) {
    this.highincrement = highincrement;
  }

  public Set<Application> getApplications() {
    return this.applications;
  }

  public void setApplications(Set<Application> applications) {
    this.applications = applications;
  }

  public String getHasminimumbase() {
    return hasminimumbase;
  }
  
  public String getHasminimumincrement() {
    return hasminimumincrement;
  }

  public long getCallprice() {
    return callprice;
  }

  public void setCallprice(long callprice) {
    this.callprice = callprice;
  }

  public String getCallunderlying() {
    return callunderlying;
  }

  public void setCallunderlying(String callunderlying) {
    this.callunderlying = callunderlying;
  }

  public double getMaxcommission() {
    return maxcommission;
  }

  public void setMaxcommission(double maxcommission) {
    this.maxcommission = maxcommission;
  }

  public long getPutprice() {
    return putprice;
  }

  public void setPutprice(long putprice) {
    this.putprice = putprice;
  }

  public String getCode() {
    return this.code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public String toString() {
    return this.name;
  }

  //~ Instance fields ----------------------------------------------------------

  private Long id;
  private Company company;
  private String name;
  private String code;
  private String type;
  private Date closingdate;
  private long putprice;
  private long callprice;
  private String callunderlying;
  private String shortdesc;
  private String hasminimumbase;
  private String hasminimumincrement;
  private long lowminimum;
  private long lowincrement;
  private long highminimum;
  private long highincrement;
  private double maxcommission;
  private Set<Application> applications;
}
