package org.opi.domain;

import java.util.HashSet;
import java.util.Set;


/**
 * Trust generated by MyEclipse - Hibernate Tools
 */

public class Trust extends org.opi.domain.BaseDomain implements java.io.Serializable {
   private static final long serialVersionUID = 10;

   // Fields
     private long id = Constants.NEW_DOMAIN_ID; // mod. by paulmac
     private Company companyByCompanyid;
     private Company companyBySolicitorcompanyid;
     private String solicitorname;
     private String issuperfund = "false";
     private String reviewdeeds = "false";
     private String wealthbyemployment = "false";
     private String wealthbyinvestments = "false";
     private String wealthbyother = "false";
     private String wealthbyotherinfo;
     private String beneficiaries;
     private Set applications = new HashSet(0);


     // Constructors

     // added by paulmac
     public Trust(long id) {
        this.id = id;
     }

     /** default constructor */
     public Trust() {
     }

   /** minimal constructor */
     public Trust(long id, String issuperfund, String reviewdeeds) {
         this.id = id;
         this.issuperfund = issuperfund;
         this.reviewdeeds = reviewdeeds;
     }

     /** full constructor */
     public Trust(long id, Company companyByCompanyid, Company companyBySolicitorcompanyid, String solicitorname, String issuperfund, String reviewdeeds, String wealthbyemployment, String wealthbyinvestments, String wealthbyother, String wealthbyotherinfo, Set applications) {
         this.id = id;
         this.companyByCompanyid = companyByCompanyid;
         this.companyBySolicitorcompanyid = companyBySolicitorcompanyid;
         this.solicitorname = solicitorname;
         this.issuperfund = issuperfund;
         this.reviewdeeds = reviewdeeds;
         this.wealthbyemployment = wealthbyemployment;
         this.wealthbyinvestments = wealthbyinvestments;
         this.wealthbyother = wealthbyother;
         this.wealthbyotherinfo = wealthbyotherinfo;
         this.applications = applications;
     }

     /** full constructor */
     public Trust clone(long id) {
         Trust clone = new Trust(id);
         if (this.companyByCompanyid != null)
         {
            Company companyByCompanyidClone = companyByCompanyid.clone(id--);
            clone.companyByCompanyid = companyByCompanyidClone;
         }
         if (this.companyBySolicitorcompanyid != null)
         {
            Company companyBySolicitorcompanyidClone = companyBySolicitorcompanyid.clone(id--);
            clone.companyBySolicitorcompanyid = companyBySolicitorcompanyidClone;
         }
         clone.solicitorname = solicitorname;
         clone.issuperfund = issuperfund;
         clone.reviewdeeds = reviewdeeds;
         clone.wealthbyemployment = wealthbyemployment;
         clone.wealthbyinvestments = wealthbyinvestments;
         clone.wealthbyother = wealthbyother;
         clone.wealthbyotherinfo = wealthbyotherinfo;
//         clone.applications = applications;
         return clone;
     }

    // Property accessors

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Company getCompanyByCompanyid() {
        return this.companyByCompanyid;
    }

    public void setCompanyByCompanyid(Company companyByCompanyid) {
        this.companyByCompanyid = companyByCompanyid;
    }

    public Company getCompanyBySolicitorcompanyid() {
        return this.companyBySolicitorcompanyid;
    }

    public void setCompanyBySolicitorcompanyid(Company companyBySolicitorcompanyid) {
        this.companyBySolicitorcompanyid = companyBySolicitorcompanyid;
    }

    public String getSolicitorname() {
        return this.solicitorname;
    }

    public void setSolicitorname(String solicitorname) {
        this.solicitorname = solicitorname;
    }

    public Set getApplications() {
        return this.applications;
    }

    public void setApplications(Set applications) {
        this.applications = applications;
    }

    public String getWealthbyemployment() {
        return this.wealthbyemployment;
    }

    public void setWealthbyemployment(String wealthbyemployment) {
        if (wealthbyemployment == null)
           this.wealthbyemployment = "false";
        else
           this.wealthbyemployment = wealthbyemployment;
    }

    public String getWealthbyinvestments() {
        return this.wealthbyinvestments;
    }

    public void setWealthbyinvestments(String wealthbyinvestments) {
        if (wealthbyinvestments == null)
           this.wealthbyinvestments = "false";
        else
           this.wealthbyinvestments = wealthbyinvestments;
    }

    public String getWealthbyother() {
        return this.wealthbyother;
    }

    public void setWealthbyother(String wealthbyother) {
        if (wealthbyother == null)
           this.wealthbyother = "false";
        else
           this.wealthbyother = wealthbyother;
    }

    public String getWealthbyotherinfo() {
        return this.wealthbyotherinfo;
    }

    public void setWealthbyotherinfo(String wealthbyotherinfo) {
        this.wealthbyotherinfo = wealthbyotherinfo;
    }


   public String getIssuperfund() {
      return issuperfund;
   }


   public void setIssuperfund(String issuperfund) {
      if (issuperfund == null)
         this.issuperfund = "false";
      else
         this.issuperfund = issuperfund;
   }


   public String getReviewdeeds()
   {
      return reviewdeeds;
   }


   public void setReviewdeeds(String reviewdeeds)
   {
      if (reviewdeeds == null)
         this.reviewdeeds = "false";
      else
         this.reviewdeeds = reviewdeeds;
   }

  public String getBeneficiaries() {
    return this.beneficiaries;
  }

  public void setBeneficiaries(String beneficiaries) {
    this.beneficiaries = beneficiaries;
  }
}